= Steckbrief Vortragsmanager
Jürgen Krey <juergen.krey@msg.group>

:toc!:
:toc-title: Inhaltsverzeichnis
:table-caption: Tabelle
:figure-caption: Abbildung
:example-caption: Beispiel

== Einleitung

Die Vortragsmanager-App dient der Organisation von Veranstaltungen, die im Wesentlichen aus Vorträgen für die Teilnehmern besteht.

Der Veranstalter gibt der organisatorischen Rahmen der Veranstaltung vor: Zeiten, Räume, Referenten, Vorträge, etc.

Die Teilnehmer äußern ihre Vortragswünsche, und die Anwendung generiert daraus
 automatisiert einen quasi-optimalen Belegungsplan für Teilnehmer sowie die Referenten mit ihren Vorträgen.

Um den Organisatoren die Erfassung zu erleichtern, erhalten Teilnehmer und Referenten individuelle Zugänge über Self-Service Portale.

Auch für die anschließende Durchführung der Veranstaltung bietet die App vielfältige Unterstützung:

* Stundenplan der Vorträge zum Überblick für alle Beteiligten
* Individuelle Laufzettel für die Teilnehmer
* Individuelle Vortragspläne für die Referenten
* Anwesenheitskontrolllisten
* Wunscherfüllungs- und Auslastungsstatistiken
* Zufriedenheitsabfragen für Teilnehmer und Referenten


== Installation

Die Anwendung besteht aus einem Web-Server mit entsprechenden Web-Seiten für alle Beteiligte, die Veranstaltungsdaten werden auf einem separaten Datenbank-Server gespeichert.

Die Anwendung liegt wahlweise als

* als Java Applikation - Mindestanforderung: Java Runtime Environment (JRE) ab Version 21 - oder
* als Binär-Image für diverse Betriebssysteme vor.


Als Datenbank ist derzeit Postgresql v.18 vorgesehen, andere relationale Datenbanksysteme, z.B. Oracle, MS SqlServer, oä. sind möglich.

Es entstehen *keine* Lizenzkosten für OpenSource Produkte.


== Betriebliche Voraussetzungen

=== Betriebssystem

Díe Anwendung wurde unter MacOS / Linux entwickelt und ist portierbar auf alle gängigen Betriebssysteme.

Die gewählte Datenbank kann auf den meisten gängigen Betriebssysteme installiert werden.


=== CPU

Im Betrieb sollten 1-2 CPUs mit 1 GHz ausreichen.

=== Speicher/RAM

Server mit 512 MB RAM  für Anwendung
Datenbank-Installation 512 MB, dazu mit 2GB RAM im Betrieb und 200 MB Storage.

=== Netzwerk

Folgende Zugriffsmöglichkeiten auf Anwendung:

.Variante A: lokale Installation auf Schulserver

* Direkte Zugriffe nur für Messe-Organisatoren und Schüler

* Self-Service für Schüler und Referenten über externe Forms-Abfrage und manuellem CSV-Import/-Update

* Eigene Administration


.Variante B: zentrale Installation (Kreis-IT / Bechtle)

* Direkte Zugriffe für Messe-Organisatoren, Schüler und Referenten

* Betrieb und Administration durch Dienstleister


=== Gesicherte Zugriffe

Nutzer identifizieren sich über Login-Id = EMailadresse
und authentifizieren sich über verschlüsseltes Kennwort.

Nutzer können die Änderung ihres Kennworts per Email anfordern, insbesondere bei Erst-Anmeldung.


== Betriebliche Fragen

* Zugriff auf Log-Dateien und Datenbank von aussen sicherstellen
* Backup-Verfahren für Datenbank implementieren

* 1./2.-Level Support: wie können Nutzer Fehler und Verbesserungen melden?

