= Automatisch generierte UseCase Dokumentation
:toc: left
:sectnums:

Per Reflection aus den `@Path`/`@GET`/.../`@RolesAllowed`-Annotationen der REST-Resource-
Klassen erzeugt (siehe `UseCaseScanner.java`) - jeder Endpunkt ist ein UseCase-Knoten im
Diagramm unten. Manuell gepflegte Querverweise, welches Benutzerhandbuch welchen UseCase
beschreibt, finden sich in den Benutzerhandbüchern selbst (Organisator/Referent/Teilnehmer) -
diese Datei wird bei jedem Lauf komplett überschrieben, daher hier bewusst keine manuell
gepflegten Inhalte. Neu erzeugen: siehe Kommentar am Kopf von `UseCaseScanner.java`.

== UseCase Diagramm (PlantUML)

[plantuml, usecase-gen, svg]
----
@startuml
left to right direction
actor "ADMINISTRATOR" as ADMINISTRATOR
actor "ORGANISATOR" as ORGANISATOR
actor "PUBLIC" as PUBLIC
actor "REFERENT" as REFERENT
actor "TEILNEHMER" as TEILNEHMER
package "KonfPlan API" {
  (getInfo) as AppInfoResource_getInfo
  (export) as DatabaseBackupResource_export
  (create) as GebaeudeResource_create
  (createRaum) as GebaeudeResource_createRaum
  (delete) as GebaeudeResource_delete
  (deleteRaum) as GebaeudeResource_deleteRaum
  (getAll) as GebaeudeResource_getAll
  (getOne) as GebaeudeResource_getOne
  (getRaeumeByGebaeude) as GebaeudeResource_getRaeumeByGebaeude
  (importGebaeude) as GebaeudeResource_importGebaeude
  (update) as GebaeudeResource_update
  (updateRaum) as GebaeudeResource_updateRaum
  (getNews) as LaufbandResource_getNews
  (getEigene) as NachrichtResource_getEigene
  (getUngeleseneAnzahl) as NachrichtResource_getUngeleseneAnzahl
  (markiereAlsGelesen) as NachrichtResource_markiereAlsGelesen
  (getAll) as NeigungResource_getAll
  (get) as OnboardingStatusResource_get
  (addGruppenkategorieWert) as OrganisatorResource_addGruppenkategorieWert
  (changeRole) as OrganisatorResource_changeRole
  (createGruppe) as OrganisatorResource_createGruppe
  (createGruppenkategorie) as OrganisatorResource_createGruppenkategorie
  (createUser) as OrganisatorResource_createUser
  (deleteGruppe) as OrganisatorResource_deleteGruppe
  (deleteGruppenkategorie) as OrganisatorResource_deleteGruppenkategorie
  (deleteGruppenkategorieWert) as OrganisatorResource_deleteGruppenkategorieWert
  (deleteUser) as OrganisatorResource_deleteUser
  (generateTeilnehmerPasswortZip) as OrganisatorResource_generateTeilnehmerPasswortZip
  (getAllUsers) as OrganisatorResource_getAllUsers
  (getGruppen) as OrganisatorResource_getGruppen
  (getGruppenkategorien) as OrganisatorResource_getGruppenkategorien
  (getRaumVerfuegbarkeiten) as OrganisatorResource_getRaumVerfuegbarkeiten
  (getTeilnehmerGruppenwerte) as OrganisatorResource_getTeilnehmerGruppenwerte
  (getUser) as OrganisatorResource_getUser
  (getVerfuegbarkeiten) as OrganisatorResource_getVerfuegbarkeiten
  (importOrganisatoren) as OrganisatorResource_importOrganisatoren
  (importPrioritaeten) as OrganisatorResource_importPrioritaeten
  (importRaumVerfuegbarkeiten) as OrganisatorResource_importRaumVerfuegbarkeiten
  (importReferentenVerfuegbarkeiten) as OrganisatorResource_importReferentenVerfuegbarkeiten
  (importTeilnehmerVerfuegbarkeiten) as OrganisatorResource_importTeilnehmerVerfuegbarkeiten
  (inviteUser) as OrganisatorResource_inviteUser
  (removeTeilnehmerGruppenwert) as OrganisatorResource_removeTeilnehmerGruppenwert
  (renameGruppe) as OrganisatorResource_renameGruppe
  (renameGruppenkategorieWert) as OrganisatorResource_renameGruppenkategorieWert
  (resetPassword) as OrganisatorResource_resetPassword
  (setTeilnehmerGruppenwert) as OrganisatorResource_setTeilnehmerGruppenwert
  (updateGruppenkategorie) as OrganisatorResource_updateGruppenkategorie
  (updateRaumVerfuegbarkeit) as OrganisatorResource_updateRaumVerfuegbarkeit
  (updateTeilnehmerPrioritaet) as OrganisatorResource_updateTeilnehmerPrioritaet
  (updateUser) as OrganisatorResource_updateUser
  (updateVerfuegbarkeit) as OrganisatorResource_updateVerfuegbarkeit
  (cancelPlanung) as PlanungResource_cancelPlanung
  (exportBundle) as PlanungResource_exportBundle
  (exportDzn) as PlanungResource_exportDzn
  (getStatus) as PlanungResource_getStatus
  (importBundle) as PlanungResource_importBundle
  (startPlanung) as PlanungResource_startPlanung
  (getPrioritaeten) as PrioritaetenResource_getPrioritaeten
  (updatePrioritaeten) as PrioritaetenResource_updatePrioritaeten
  (getAllProtokollEntries) as ProtokollResource_getAllProtokollEntries
  (cloneTalkForEvent) as ReferentResource_cloneTalkForEvent
  (createVortrag) as ReferentResource_createVortrag
  (deleteVortrag) as ReferentResource_deleteVortrag
  (getMyPlan) as ReferentResource_getMyPlan
  (getReferent) as ReferentResource_getReferent
  (getReferentVeranstaltungen) as ReferentResource_getReferentVeranstaltungen
  (getReferentenVortraege) as ReferentResource_getReferentenVortraege
  (getVerfuegbarkeiten) as ReferentResource_getVerfuegbarkeiten
  (meldeVortragFuerVeranstaltungAb) as ReferentResource_meldeVortragFuerVeranstaltungAb
  (meldeVortragFuerVeranstaltungAn) as ReferentResource_meldeVortragFuerVeranstaltungAn
  (updateProfile) as ReferentResource_updateProfile
  (updateVerfuegbarkeit) as ReferentResource_updateVerfuegbarkeit
  (updateVortrag) as ReferentResource_updateVortrag
  (getAbstimmungsfragebogenData) as ReportResource_getAbstimmungsfragebogenData
  (getAlleLaufzettelData) as ReportResource_getAlleLaufzettelData
  (getAlleLaufzettelReferentenData) as ReportResource_getAlleLaufzettelReferentenData
  (getAlleRaumschilderData) as ReportResource_getAlleRaumschilderData
  (getFreieSlotsReferentenData) as ReportResource_getFreieSlotsReferentenData
  (getFreieSlotsTeilnehmerData) as ReportResource_getFreieSlotsTeilnehmerData
  (getLaufzettelReferentData) as ReportResource_getLaufzettelReferentData
  (getLaufzettelTeilnehmerData) as ReportResource_getLaufzettelTeilnehmerData
  (getPriosDashboardData) as ReportResource_getPriosDashboardData
  (getStundenplanData) as ReportResource_getStundenplanData
  (getTeilnehmerDashboardData) as ReportResource_getTeilnehmerDashboardData
  (getUebersichtRaeumeData) as ReportResource_getUebersichtRaeumeData
  (getVortragAnmeldungenData) as ReportResource_getVortragAnmeldungenData
  (getWahlvortraegeAnmeldungenUebersichtData) as ReportResource_getWahlvortraegeAnmeldungenUebersichtData
  (getAll) as SlotResource_getAll
  (createTeilnehmer) as TeilnehmerResource_createTeilnehmer
  (deleteTeilnehmer) as TeilnehmerResource_deleteTeilnehmer
  (getAlleVeranstaltungsteilnehmer) as TeilnehmerResource_getAlleVeranstaltungsteilnehmer
  (getMeineVortraege) as TeilnehmerResource_getMeineVortraege
  (getPlan) as TeilnehmerResource_getPlan
  (getTeilnehmer) as TeilnehmerResource_getTeilnehmer
  (getTeilnehmerProfile) as TeilnehmerResource_getTeilnehmerProfile
  (getTeilnehmerVeranstaltungen) as TeilnehmerResource_getTeilnehmerVeranstaltungen
  (getVerfuegbarkeiten) as TeilnehmerResource_getVerfuegbarkeiten
  (toggleActive) as TeilnehmerResource_toggleActive
  (updateTeilnehmer) as TeilnehmerResource_updateTeilnehmer
  (updateTeilnehmerProfile) as TeilnehmerResource_updateTeilnehmerProfile
  (updateVerfuegbarkeit) as TeilnehmerResource_updateVerfuegbarkeit
  (importDataset) as VeranstaltungImportResource_importDataset
  (importZip) as VeranstaltungImportResource_importZip
  (listDatasets) as VeranstaltungImportResource_listDatasets
  (create) as VeranstaltungResource_create
  (createNutzer) as VeranstaltungResource_createNutzer
  (createSlot) as VeranstaltungResource_createSlot
  (createVortrag) as VeranstaltungResource_createVortrag
  (delete) as VeranstaltungResource_delete
  (deleteNutzer) as VeranstaltungResource_deleteNutzer
  (deleteSlot) as VeranstaltungResource_deleteSlot
  (deleteVortrag) as VeranstaltungResource_deleteVortrag
  (getAktuelleZuweisungen) as VeranstaltungResource_getAktuelleZuweisungen
  (getAll) as VeranstaltungResource_getAll
  (getDetaillierterPlan) as VeranstaltungResource_getDetaillierterPlan
  (getGesamtplan) as VeranstaltungResource_getGesamtplan
  (getNutzer) as VeranstaltungResource_getNutzer
  (getOne) as VeranstaltungResource_getOne
  (getPlanQualitaet) as VeranstaltungResource_getPlanQualitaet
  (getRaumUmbuchungOptionen) as VeranstaltungResource_getRaumUmbuchungOptionen
  (getRaumVerfuegbarkeiten) as VeranstaltungResource_getRaumVerfuegbarkeiten
  (getSlots) as VeranstaltungResource_getSlots
  (getStats) as VeranstaltungResource_getStats
  (getUmbuchungsOptionen) as VeranstaltungResource_getUmbuchungsOptionen
  (getVeranstaltungsVortrag) as VeranstaltungResource_getVeranstaltungsVortrag
  (getVortraege) as VeranstaltungResource_getVortraege
  (getWahlvortragInstanzen) as VeranstaltungResource_getWahlvortragInstanzen
  (importReferenten) as VeranstaltungResource_importReferenten
  (importSlots) as VeranstaltungResource_importSlots
  (importVeranstaltungen) as VeranstaltungResource_importVeranstaltungen
  (importVortraege) as VeranstaltungResource_importVortraege
  (listePlanungsergebnisse) as VeranstaltungResource_listePlanungsergebnisse
  (loescheErgebnis) as VeranstaltungResource_loescheErgebnis
  (publiziereErgebnis) as VeranstaltungResource_publiziereErgebnis
  (sendeNachricht) as VeranstaltungResource_sendeNachricht
  (teilnehmerNachbuchen) as VeranstaltungResource_teilnehmerNachbuchen
  (teilnehmerUmbuchen) as VeranstaltungResource_teilnehmerUmbuchen
  (update) as VeranstaltungResource_update
  (updateNutzer) as VeranstaltungResource_updateNutzer
  (updateSlot) as VeranstaltungResource_updateSlot
  (updateVortrag) as VeranstaltungResource_updateVortrag
  (uploadTeilnehmerCsv) as VeranstaltungResource_uploadTeilnehmerCsv
  (vortragsInstanzRaumUmbuchen) as VeranstaltungResource_vortragsInstanzRaumUmbuchen
  (vortragsInstanzUmplanen) as VeranstaltungResource_vortragsInstanzUmplanen
  (zurueckziehenErgebnis) as VeranstaltungResource_zurueckziehenErgebnis
  (create) as VerbesserungsvorschlagResource_create
  (delete) as VerbesserungsvorschlagResource_delete
  (getAll) as VerbesserungsvorschlagResource_getAll
  (updateStatus) as VerbesserungsvorschlagResource_updateStatus
  (get) as WartungshinweisResource_get
  (loeschen) as WartungshinweisResource_loeschen
  (setzen) as WartungshinweisResource_setzen
  (getOrganisatorKalender) as KalenderResource_getOrganisatorKalender
  (getReferentKalender) as KalenderResource_getReferentKalender
  (getTeilnehmerKalender) as KalenderResource_getTeilnehmerKalender
}
ADMINISTRATOR --> DatabaseBackupResource_export
ADMINISTRATOR --> GebaeudeResource_create
ADMINISTRATOR --> GebaeudeResource_createRaum
ADMINISTRATOR --> GebaeudeResource_delete
ADMINISTRATOR --> GebaeudeResource_deleteRaum
ADMINISTRATOR --> GebaeudeResource_getAll
ADMINISTRATOR --> GebaeudeResource_getOne
ADMINISTRATOR --> GebaeudeResource_getRaeumeByGebaeude
ADMINISTRATOR --> GebaeudeResource_importGebaeude
ADMINISTRATOR --> GebaeudeResource_update
ADMINISTRATOR --> GebaeudeResource_updateRaum
ADMINISTRATOR --> NachrichtResource_getEigene
ADMINISTRATOR --> NachrichtResource_getUngeleseneAnzahl
ADMINISTRATOR --> NachrichtResource_markiereAlsGelesen
ADMINISTRATOR --> NeigungResource_getAll
ADMINISTRATOR --> OnboardingStatusResource_get
ADMINISTRATOR --> OrganisatorResource_addGruppenkategorieWert
ADMINISTRATOR --> OrganisatorResource_changeRole
ADMINISTRATOR --> OrganisatorResource_createGruppe
ADMINISTRATOR --> OrganisatorResource_createGruppenkategorie
ADMINISTRATOR --> OrganisatorResource_createUser
ADMINISTRATOR --> OrganisatorResource_deleteGruppe
ADMINISTRATOR --> OrganisatorResource_deleteGruppenkategorie
ADMINISTRATOR --> OrganisatorResource_deleteGruppenkategorieWert
ADMINISTRATOR --> OrganisatorResource_deleteUser
ADMINISTRATOR --> OrganisatorResource_generateTeilnehmerPasswortZip
ADMINISTRATOR --> OrganisatorResource_getAllUsers
ADMINISTRATOR --> OrganisatorResource_getGruppen
ADMINISTRATOR --> OrganisatorResource_getGruppenkategorien
ADMINISTRATOR --> OrganisatorResource_getRaumVerfuegbarkeiten
ADMINISTRATOR --> OrganisatorResource_getTeilnehmerGruppenwerte
ADMINISTRATOR --> OrganisatorResource_getUser
ADMINISTRATOR --> OrganisatorResource_getVerfuegbarkeiten
ADMINISTRATOR --> OrganisatorResource_importOrganisatoren
ADMINISTRATOR --> OrganisatorResource_importPrioritaeten
ADMINISTRATOR --> OrganisatorResource_importRaumVerfuegbarkeiten
ADMINISTRATOR --> OrganisatorResource_importReferentenVerfuegbarkeiten
ADMINISTRATOR --> OrganisatorResource_importTeilnehmerVerfuegbarkeiten
ADMINISTRATOR --> OrganisatorResource_inviteUser
ADMINISTRATOR --> OrganisatorResource_removeTeilnehmerGruppenwert
ADMINISTRATOR --> OrganisatorResource_renameGruppe
ADMINISTRATOR --> OrganisatorResource_renameGruppenkategorieWert
ADMINISTRATOR --> OrganisatorResource_resetPassword
ADMINISTRATOR --> OrganisatorResource_setTeilnehmerGruppenwert
ADMINISTRATOR --> OrganisatorResource_updateGruppenkategorie
ADMINISTRATOR --> OrganisatorResource_updateRaumVerfuegbarkeit
ADMINISTRATOR --> OrganisatorResource_updateTeilnehmerPrioritaet
ADMINISTRATOR --> OrganisatorResource_updateUser
ADMINISTRATOR --> OrganisatorResource_updateVerfuegbarkeit
ADMINISTRATOR --> PlanungResource_cancelPlanung
ADMINISTRATOR --> PlanungResource_exportBundle
ADMINISTRATOR --> PlanungResource_exportDzn
ADMINISTRATOR --> PlanungResource_getStatus
ADMINISTRATOR --> PlanungResource_importBundle
ADMINISTRATOR --> PlanungResource_startPlanung
ADMINISTRATOR --> PrioritaetenResource_getPrioritaeten
ADMINISTRATOR --> PrioritaetenResource_updatePrioritaeten
ADMINISTRATOR --> ProtokollResource_getAllProtokollEntries
ADMINISTRATOR --> ReferentResource_cloneTalkForEvent
ADMINISTRATOR --> ReferentResource_createVortrag
ADMINISTRATOR --> ReferentResource_deleteVortrag
ADMINISTRATOR --> ReferentResource_getMyPlan
ADMINISTRATOR --> ReferentResource_getReferent
ADMINISTRATOR --> ReferentResource_getReferentVeranstaltungen
ADMINISTRATOR --> ReferentResource_getReferentenVortraege
ADMINISTRATOR --> ReferentResource_getVerfuegbarkeiten
ADMINISTRATOR --> ReferentResource_meldeVortragFuerVeranstaltungAb
ADMINISTRATOR --> ReferentResource_meldeVortragFuerVeranstaltungAn
ADMINISTRATOR --> ReferentResource_updateProfile
ADMINISTRATOR --> ReferentResource_updateVerfuegbarkeit
ADMINISTRATOR --> ReferentResource_updateVortrag
ADMINISTRATOR --> ReportResource_getAbstimmungsfragebogenData
ADMINISTRATOR --> ReportResource_getAlleLaufzettelData
ADMINISTRATOR --> ReportResource_getAlleLaufzettelReferentenData
ADMINISTRATOR --> ReportResource_getAlleRaumschilderData
ADMINISTRATOR --> ReportResource_getFreieSlotsReferentenData
ADMINISTRATOR --> ReportResource_getFreieSlotsTeilnehmerData
ADMINISTRATOR --> ReportResource_getLaufzettelReferentData
ADMINISTRATOR --> ReportResource_getLaufzettelTeilnehmerData
ADMINISTRATOR --> ReportResource_getPriosDashboardData
ADMINISTRATOR --> ReportResource_getStundenplanData
ADMINISTRATOR --> ReportResource_getTeilnehmerDashboardData
ADMINISTRATOR --> ReportResource_getUebersichtRaeumeData
ADMINISTRATOR --> ReportResource_getVortragAnmeldungenData
ADMINISTRATOR --> ReportResource_getWahlvortraegeAnmeldungenUebersichtData
ADMINISTRATOR --> SlotResource_getAll
ADMINISTRATOR --> TeilnehmerResource_createTeilnehmer
ADMINISTRATOR --> TeilnehmerResource_deleteTeilnehmer
ADMINISTRATOR --> TeilnehmerResource_getAlleVeranstaltungsteilnehmer
ADMINISTRATOR --> TeilnehmerResource_getTeilnehmer
ADMINISTRATOR --> TeilnehmerResource_toggleActive
ADMINISTRATOR --> TeilnehmerResource_updateTeilnehmer
ADMINISTRATOR --> VeranstaltungImportResource_importDataset
ADMINISTRATOR --> VeranstaltungImportResource_importZip
ADMINISTRATOR --> VeranstaltungImportResource_listDatasets
ADMINISTRATOR --> VeranstaltungResource_create
ADMINISTRATOR --> VeranstaltungResource_createNutzer
ADMINISTRATOR --> VeranstaltungResource_createSlot
ADMINISTRATOR --> VeranstaltungResource_createVortrag
ADMINISTRATOR --> VeranstaltungResource_delete
ADMINISTRATOR --> VeranstaltungResource_deleteNutzer
ADMINISTRATOR --> VeranstaltungResource_deleteSlot
ADMINISTRATOR --> VeranstaltungResource_deleteVortrag
ADMINISTRATOR --> VeranstaltungResource_getAktuelleZuweisungen
ADMINISTRATOR --> VeranstaltungResource_getAll
ADMINISTRATOR --> VeranstaltungResource_getDetaillierterPlan
ADMINISTRATOR --> VeranstaltungResource_getGesamtplan
ADMINISTRATOR --> VeranstaltungResource_getNutzer
ADMINISTRATOR --> VeranstaltungResource_getOne
ADMINISTRATOR --> VeranstaltungResource_getPlanQualitaet
ADMINISTRATOR --> VeranstaltungResource_getRaumUmbuchungOptionen
ADMINISTRATOR --> VeranstaltungResource_getRaumVerfuegbarkeiten
ADMINISTRATOR --> VeranstaltungResource_getSlots
ADMINISTRATOR --> VeranstaltungResource_getStats
ADMINISTRATOR --> VeranstaltungResource_getUmbuchungsOptionen
ADMINISTRATOR --> VeranstaltungResource_getVeranstaltungsVortrag
ADMINISTRATOR --> VeranstaltungResource_getVortraege
ADMINISTRATOR --> VeranstaltungResource_getWahlvortragInstanzen
ADMINISTRATOR --> VeranstaltungResource_importReferenten
ADMINISTRATOR --> VeranstaltungResource_importSlots
ADMINISTRATOR --> VeranstaltungResource_importVeranstaltungen
ADMINISTRATOR --> VeranstaltungResource_importVortraege
ADMINISTRATOR --> VeranstaltungResource_listePlanungsergebnisse
ADMINISTRATOR --> VeranstaltungResource_loescheErgebnis
ADMINISTRATOR --> VeranstaltungResource_publiziereErgebnis
ADMINISTRATOR --> VeranstaltungResource_sendeNachricht
ADMINISTRATOR --> VeranstaltungResource_teilnehmerNachbuchen
ADMINISTRATOR --> VeranstaltungResource_teilnehmerUmbuchen
ADMINISTRATOR --> VeranstaltungResource_update
ADMINISTRATOR --> VeranstaltungResource_updateNutzer
ADMINISTRATOR --> VeranstaltungResource_updateSlot
ADMINISTRATOR --> VeranstaltungResource_updateVortrag
ADMINISTRATOR --> VeranstaltungResource_uploadTeilnehmerCsv
ADMINISTRATOR --> VeranstaltungResource_vortragsInstanzRaumUmbuchen
ADMINISTRATOR --> VeranstaltungResource_vortragsInstanzUmplanen
ADMINISTRATOR --> VeranstaltungResource_zurueckziehenErgebnis
ADMINISTRATOR --> VerbesserungsvorschlagResource_create
ADMINISTRATOR --> VerbesserungsvorschlagResource_delete
ADMINISTRATOR --> VerbesserungsvorschlagResource_getAll
ADMINISTRATOR --> VerbesserungsvorschlagResource_updateStatus
ADMINISTRATOR --> WartungshinweisResource_get
ADMINISTRATOR --> WartungshinweisResource_loeschen
ADMINISTRATOR --> WartungshinweisResource_setzen
ADMINISTRATOR --> KalenderResource_getOrganisatorKalender
ORGANISATOR --> GebaeudeResource_create
ORGANISATOR --> GebaeudeResource_createRaum
ORGANISATOR --> GebaeudeResource_delete
ORGANISATOR --> GebaeudeResource_deleteRaum
ORGANISATOR --> GebaeudeResource_getAll
ORGANISATOR --> GebaeudeResource_getOne
ORGANISATOR --> GebaeudeResource_getRaeumeByGebaeude
ORGANISATOR --> GebaeudeResource_importGebaeude
ORGANISATOR --> GebaeudeResource_update
ORGANISATOR --> GebaeudeResource_updateRaum
ORGANISATOR --> NachrichtResource_getEigene
ORGANISATOR --> NachrichtResource_getUngeleseneAnzahl
ORGANISATOR --> NachrichtResource_markiereAlsGelesen
ORGANISATOR --> NeigungResource_getAll
ORGANISATOR --> OnboardingStatusResource_get
ORGANISATOR --> OrganisatorResource_addGruppenkategorieWert
ORGANISATOR --> OrganisatorResource_changeRole
ORGANISATOR --> OrganisatorResource_createGruppe
ORGANISATOR --> OrganisatorResource_createGruppenkategorie
ORGANISATOR --> OrganisatorResource_createUser
ORGANISATOR --> OrganisatorResource_deleteGruppe
ORGANISATOR --> OrganisatorResource_deleteGruppenkategorie
ORGANISATOR --> OrganisatorResource_deleteGruppenkategorieWert
ORGANISATOR --> OrganisatorResource_deleteUser
ORGANISATOR --> OrganisatorResource_generateTeilnehmerPasswortZip
ORGANISATOR --> OrganisatorResource_getAllUsers
ORGANISATOR --> OrganisatorResource_getGruppen
ORGANISATOR --> OrganisatorResource_getGruppenkategorien
ORGANISATOR --> OrganisatorResource_getRaumVerfuegbarkeiten
ORGANISATOR --> OrganisatorResource_getTeilnehmerGruppenwerte
ORGANISATOR --> OrganisatorResource_getUser
ORGANISATOR --> OrganisatorResource_getVerfuegbarkeiten
ORGANISATOR --> OrganisatorResource_importOrganisatoren
ORGANISATOR --> OrganisatorResource_importPrioritaeten
ORGANISATOR --> OrganisatorResource_importRaumVerfuegbarkeiten
ORGANISATOR --> OrganisatorResource_importReferentenVerfuegbarkeiten
ORGANISATOR --> OrganisatorResource_importTeilnehmerVerfuegbarkeiten
ORGANISATOR --> OrganisatorResource_inviteUser
ORGANISATOR --> OrganisatorResource_removeTeilnehmerGruppenwert
ORGANISATOR --> OrganisatorResource_renameGruppe
ORGANISATOR --> OrganisatorResource_renameGruppenkategorieWert
ORGANISATOR --> OrganisatorResource_resetPassword
ORGANISATOR --> OrganisatorResource_setTeilnehmerGruppenwert
ORGANISATOR --> OrganisatorResource_updateGruppenkategorie
ORGANISATOR --> OrganisatorResource_updateRaumVerfuegbarkeit
ORGANISATOR --> OrganisatorResource_updateTeilnehmerPrioritaet
ORGANISATOR --> OrganisatorResource_updateUser
ORGANISATOR --> OrganisatorResource_updateVerfuegbarkeit
ORGANISATOR --> PlanungResource_cancelPlanung
ORGANISATOR --> PlanungResource_exportBundle
ORGANISATOR --> PlanungResource_exportDzn
ORGANISATOR --> PlanungResource_getStatus
ORGANISATOR --> PlanungResource_importBundle
ORGANISATOR --> PlanungResource_startPlanung
ORGANISATOR --> PrioritaetenResource_getPrioritaeten
ORGANISATOR --> PrioritaetenResource_updatePrioritaeten
ORGANISATOR --> ProtokollResource_getAllProtokollEntries
ORGANISATOR --> ReferentResource_cloneTalkForEvent
ORGANISATOR --> ReferentResource_createVortrag
ORGANISATOR --> ReferentResource_deleteVortrag
ORGANISATOR --> ReferentResource_getMyPlan
ORGANISATOR --> ReferentResource_getReferent
ORGANISATOR --> ReferentResource_getReferentVeranstaltungen
ORGANISATOR --> ReferentResource_getReferentenVortraege
ORGANISATOR --> ReferentResource_getVerfuegbarkeiten
ORGANISATOR --> ReferentResource_meldeVortragFuerVeranstaltungAb
ORGANISATOR --> ReferentResource_meldeVortragFuerVeranstaltungAn
ORGANISATOR --> ReferentResource_updateProfile
ORGANISATOR --> ReferentResource_updateVerfuegbarkeit
ORGANISATOR --> ReferentResource_updateVortrag
ORGANISATOR --> ReportResource_getAbstimmungsfragebogenData
ORGANISATOR --> ReportResource_getAlleLaufzettelData
ORGANISATOR --> ReportResource_getAlleLaufzettelReferentenData
ORGANISATOR --> ReportResource_getAlleRaumschilderData
ORGANISATOR --> ReportResource_getFreieSlotsReferentenData
ORGANISATOR --> ReportResource_getFreieSlotsTeilnehmerData
ORGANISATOR --> ReportResource_getLaufzettelReferentData
ORGANISATOR --> ReportResource_getLaufzettelTeilnehmerData
ORGANISATOR --> ReportResource_getPriosDashboardData
ORGANISATOR --> ReportResource_getStundenplanData
ORGANISATOR --> ReportResource_getTeilnehmerDashboardData
ORGANISATOR --> ReportResource_getUebersichtRaeumeData
ORGANISATOR --> ReportResource_getVortragAnmeldungenData
ORGANISATOR --> ReportResource_getWahlvortraegeAnmeldungenUebersichtData
ORGANISATOR --> SlotResource_getAll
ORGANISATOR --> TeilnehmerResource_createTeilnehmer
ORGANISATOR --> TeilnehmerResource_deleteTeilnehmer
ORGANISATOR --> TeilnehmerResource_getAlleVeranstaltungsteilnehmer
ORGANISATOR --> TeilnehmerResource_getTeilnehmer
ORGANISATOR --> TeilnehmerResource_toggleActive
ORGANISATOR --> TeilnehmerResource_updateTeilnehmer
ORGANISATOR --> VeranstaltungResource_create
ORGANISATOR --> VeranstaltungResource_createNutzer
ORGANISATOR --> VeranstaltungResource_createSlot
ORGANISATOR --> VeranstaltungResource_createVortrag
ORGANISATOR --> VeranstaltungResource_delete
ORGANISATOR --> VeranstaltungResource_deleteNutzer
ORGANISATOR --> VeranstaltungResource_deleteSlot
ORGANISATOR --> VeranstaltungResource_deleteVortrag
ORGANISATOR --> VeranstaltungResource_getAktuelleZuweisungen
ORGANISATOR --> VeranstaltungResource_getAll
ORGANISATOR --> VeranstaltungResource_getDetaillierterPlan
ORGANISATOR --> VeranstaltungResource_getGesamtplan
ORGANISATOR --> VeranstaltungResource_getNutzer
ORGANISATOR --> VeranstaltungResource_getOne
ORGANISATOR --> VeranstaltungResource_getPlanQualitaet
ORGANISATOR --> VeranstaltungResource_getRaumUmbuchungOptionen
ORGANISATOR --> VeranstaltungResource_getRaumVerfuegbarkeiten
ORGANISATOR --> VeranstaltungResource_getSlots
ORGANISATOR --> VeranstaltungResource_getStats
ORGANISATOR --> VeranstaltungResource_getUmbuchungsOptionen
ORGANISATOR --> VeranstaltungResource_getVeranstaltungsVortrag
ORGANISATOR --> VeranstaltungResource_getVortraege
ORGANISATOR --> VeranstaltungResource_getWahlvortragInstanzen
ORGANISATOR --> VeranstaltungResource_importReferenten
ORGANISATOR --> VeranstaltungResource_importSlots
ORGANISATOR --> VeranstaltungResource_importVeranstaltungen
ORGANISATOR --> VeranstaltungResource_importVortraege
ORGANISATOR --> VeranstaltungResource_listePlanungsergebnisse
ORGANISATOR --> VeranstaltungResource_loescheErgebnis
ORGANISATOR --> VeranstaltungResource_publiziereErgebnis
ORGANISATOR --> VeranstaltungResource_sendeNachricht
ORGANISATOR --> VeranstaltungResource_teilnehmerNachbuchen
ORGANISATOR --> VeranstaltungResource_teilnehmerUmbuchen
ORGANISATOR --> VeranstaltungResource_update
ORGANISATOR --> VeranstaltungResource_updateNutzer
ORGANISATOR --> VeranstaltungResource_updateSlot
ORGANISATOR --> VeranstaltungResource_updateVortrag
ORGANISATOR --> VeranstaltungResource_uploadTeilnehmerCsv
ORGANISATOR --> VeranstaltungResource_vortragsInstanzRaumUmbuchen
ORGANISATOR --> VeranstaltungResource_vortragsInstanzUmplanen
ORGANISATOR --> VeranstaltungResource_zurueckziehenErgebnis
ORGANISATOR --> VerbesserungsvorschlagResource_create
ORGANISATOR --> VerbesserungsvorschlagResource_delete
ORGANISATOR --> VerbesserungsvorschlagResource_getAll
ORGANISATOR --> VerbesserungsvorschlagResource_updateStatus
ORGANISATOR --> WartungshinweisResource_get
ORGANISATOR --> KalenderResource_getOrganisatorKalender
PUBLIC --> AppInfoResource_getInfo
PUBLIC --> LaufbandResource_getNews
REFERENT --> NachrichtResource_getEigene
REFERENT --> NachrichtResource_getUngeleseneAnzahl
REFERENT --> NachrichtResource_markiereAlsGelesen
REFERENT --> NeigungResource_getAll
REFERENT --> ReferentResource_cloneTalkForEvent
REFERENT --> ReferentResource_createVortrag
REFERENT --> ReferentResource_deleteVortrag
REFERENT --> ReferentResource_getMyPlan
REFERENT --> ReferentResource_getReferent
REFERENT --> ReferentResource_getReferentVeranstaltungen
REFERENT --> ReferentResource_getReferentenVortraege
REFERENT --> ReferentResource_getVerfuegbarkeiten
REFERENT --> ReferentResource_meldeVortragFuerVeranstaltungAb
REFERENT --> ReferentResource_meldeVortragFuerVeranstaltungAn
REFERENT --> ReferentResource_updateProfile
REFERENT --> ReferentResource_updateVerfuegbarkeit
REFERENT --> ReferentResource_updateVortrag
REFERENT --> ReportResource_getLaufzettelReferentData
REFERENT --> SlotResource_getAll
REFERENT --> VeranstaltungResource_getSlots
REFERENT --> VeranstaltungResource_getVortraege
REFERENT --> VerbesserungsvorschlagResource_create
REFERENT --> WartungshinweisResource_get
REFERENT --> KalenderResource_getReferentKalender
TEILNEHMER --> NachrichtResource_getEigene
TEILNEHMER --> NachrichtResource_getUngeleseneAnzahl
TEILNEHMER --> NachrichtResource_markiereAlsGelesen
TEILNEHMER --> NeigungResource_getAll
TEILNEHMER --> PrioritaetenResource_getPrioritaeten
TEILNEHMER --> PrioritaetenResource_updatePrioritaeten
TEILNEHMER --> ReportResource_getLaufzettelTeilnehmerData
TEILNEHMER --> ReportResource_getTeilnehmerDashboardData
TEILNEHMER --> SlotResource_getAll
TEILNEHMER --> TeilnehmerResource_getMeineVortraege
TEILNEHMER --> TeilnehmerResource_getPlan
TEILNEHMER --> TeilnehmerResource_getTeilnehmerProfile
TEILNEHMER --> TeilnehmerResource_getTeilnehmerVeranstaltungen
TEILNEHMER --> TeilnehmerResource_getVerfuegbarkeiten
TEILNEHMER --> TeilnehmerResource_updateTeilnehmerProfile
TEILNEHMER --> TeilnehmerResource_updateVerfuegbarkeit
TEILNEHMER --> VeranstaltungResource_getSlots
TEILNEHMER --> VeranstaltungResource_getVortraege
TEILNEHMER --> VerbesserungsvorschlagResource_create
TEILNEHMER --> WartungshinweisResource_get
TEILNEHMER --> KalenderResource_getTeilnehmerKalender
@enduml
----

== API Endpunkte & Rollen

=== AppInfoResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getInfo
| GET
| `/api/info`
| PUBLIC
|===

=== DatabaseBackupResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| export
| GET
| `/api/administrator/backup/export`
| ADMINISTRATOR
|===

=== GebaeudeResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| create
| POST
| `/api/gebaeude`
| ORGANISATOR, ADMINISTRATOR
| createRaum
| POST
| `/api/gebaeude/{gid}/raeume`
| ORGANISATOR, ADMINISTRATOR
| delete
| DELETE
| `/api/gebaeude/{id}`
| ORGANISATOR, ADMINISTRATOR
| deleteRaum
| DELETE
| `/api/gebaeude/{gid}/raeume/{rid}`
| ORGANISATOR, ADMINISTRATOR
| getAll
| GET
| `/api/gebaeude`
| ORGANISATOR, ADMINISTRATOR
| getOne
| GET
| `/api/gebaeude/{id}`
| ORGANISATOR, ADMINISTRATOR
| getRaeumeByGebaeude
| GET
| `/api/gebaeude/{gid}/raeume`
| ORGANISATOR, ADMINISTRATOR
| importGebaeude
| POST
| `/api/gebaeude/import`
| ORGANISATOR, ADMINISTRATOR
| update
| PUT
| `/api/gebaeude/{id}`
| ORGANISATOR, ADMINISTRATOR
| updateRaum
| PUT
| `/api/gebaeude/{gid}/raeume/{rid}`
| ORGANISATOR, ADMINISTRATOR
|===

=== LaufbandResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getNews
| GET
| `/api/laufband`
| PUBLIC
|===

=== NachrichtResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getEigene
| GET
| `/api/nachrichten`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
| getUngeleseneAnzahl
| GET
| `/api/nachrichten/ungelesen-anzahl`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
| markiereAlsGelesen
| PUT
| `/api/nachrichten/{id}/gelesen`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
|===

=== NeigungResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAll
| GET
| `/api/neigungen`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
|===

=== OnboardingStatusResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| get
| GET
| `/api/organisator/onboarding-status`
| ORGANISATOR, ADMINISTRATOR
|===

=== OrganisatorResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| addGruppenkategorieWert
| POST
| `/api/organisator/gruppenkategorien/{kategorieId}/werte`
| ORGANISATOR, ADMINISTRATOR
| changeRole
| PUT
| `/api/organisator/nutzer/{id}/rolle`
| ORGANISATOR, ADMINISTRATOR
| createGruppe
| POST
| `/api/organisator/veranstaltungen/{vid}/gruppen`
| ORGANISATOR, ADMINISTRATOR
| createGruppenkategorie
| POST
| `/api/organisator/veranstaltungen/{vid}/gruppenkategorien`
| ORGANISATOR, ADMINISTRATOR
| createUser
| POST
| `/api/organisator/nutzer`
| ORGANISATOR, ADMINISTRATOR
| deleteGruppe
| DELETE
| `/api/organisator/veranstaltungen/{vid}/gruppen/{gruppenName}`
| ORGANISATOR, ADMINISTRATOR
| deleteGruppenkategorie
| DELETE
| `/api/organisator/gruppenkategorien/{kategorieId}`
| ORGANISATOR, ADMINISTRATOR
| deleteGruppenkategorieWert
| DELETE
| `/api/organisator/gruppenkategorien/werte/{wertId}`
| ORGANISATOR, ADMINISTRATOR
| deleteUser
| DELETE
| `/api/organisator/nutzer/{id}`
| ORGANISATOR, ADMINISTRATOR
| generateTeilnehmerPasswortZip
| POST
| `/api/organisator/veranstaltungen/{vid}/teilnehmer/passwoerter/zip`
| ORGANISATOR, ADMINISTRATOR
| getAllUsers
| GET
| `/api/organisator/nutzer`
| ORGANISATOR, ADMINISTRATOR
| getGruppen
| GET
| `/api/organisator/veranstaltungen/{vid}/gruppen`
| ORGANISATOR, ADMINISTRATOR
| getGruppenkategorien
| GET
| `/api/organisator/veranstaltungen/{vid}/gruppenkategorien`
| ORGANISATOR, ADMINISTRATOR
| getRaumVerfuegbarkeiten
| GET
| `/api/organisator/veranstaltungen/{vid}/raeume/verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR
| getTeilnehmerGruppenwerte
| GET
| `/api/organisator/teilnehmer/{tid}/gruppenwerte`
| ORGANISATOR, ADMINISTRATOR
| getUser
| GET
| `/api/organisator/nutzer/{id}`
| ORGANISATOR, ADMINISTRATOR
| getVerfuegbarkeiten
| GET
| `/api/organisator/veranstaltungen/{vid}/verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR
| importOrganisatoren
| POST
| `/api/organisator/organisatoren/import`
| ORGANISATOR, ADMINISTRATOR
| importPrioritaeten
| POST
| `/api/organisator/veranstaltungen/{vid}/prioritaeten/import`
| ORGANISATOR, ADMINISTRATOR
| importRaumVerfuegbarkeiten
| POST
| `/api/organisator/veranstaltungen/{vid}/raeume/verfuegbarkeiten/import`
| ORGANISATOR, ADMINISTRATOR
| importReferentenVerfuegbarkeiten
| POST
| `/api/organisator/veranstaltungen/{vid}/referenten/verfuegbarkeiten/import`
| ORGANISATOR, ADMINISTRATOR
| importTeilnehmerVerfuegbarkeiten
| POST
| `/api/organisator/veranstaltungen/{vid}/teilnehmer/verfuegbarkeiten/import`
| ORGANISATOR, ADMINISTRATOR
| inviteUser
| POST
| `/api/organisator/nutzer/{userId}/einladen/{eventId}`
| ORGANISATOR, ADMINISTRATOR
| removeTeilnehmerGruppenwert
| DELETE
| `/api/organisator/teilnehmer/{tid}/gruppenwerte/{wertId}`
| ORGANISATOR, ADMINISTRATOR
| renameGruppe
| PUT
| `/api/organisator/veranstaltungen/{vid}/gruppen`
| ORGANISATOR, ADMINISTRATOR
| renameGruppenkategorieWert
| PUT
| `/api/organisator/gruppenkategorien/werte/{wertId}`
| ORGANISATOR, ADMINISTRATOR
| resetPassword
| POST
| `/api/organisator/nutzer/{id}/reset-password`
| ORGANISATOR, ADMINISTRATOR
| setTeilnehmerGruppenwert
| POST
| `/api/organisator/teilnehmer/{tid}/gruppenwerte/{wertId}`
| ORGANISATOR, ADMINISTRATOR
| updateGruppenkategorie
| PUT
| `/api/organisator/gruppenkategorien/{kategorieId}`
| ORGANISATOR, ADMINISTRATOR
| updateRaumVerfuegbarkeit
| POST
| `/api/organisator/veranstaltungen/{vid}/raeume/verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR
| updateTeilnehmerPrioritaet
| PUT
| `/api/organisator/veranstaltungen/{vid}/teilnehmer/{tid}/priorities`
| ORGANISATOR, ADMINISTRATOR
| updateUser
| PUT
| `/api/organisator/nutzer/{id}`
| ORGANISATOR, ADMINISTRATOR
| updateVerfuegbarkeit
| POST
| `/api/organisator/veranstaltungen/{vid}/verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR
|===

=== PlanungResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| cancelPlanung
| DELETE
| `/api/planungen/`
| ORGANISATOR, ADMINISTRATOR
| exportBundle
| POST
| `/api/planungen/{vid}/export`
| ORGANISATOR, ADMINISTRATOR
| exportDzn
| POST
| `/api/planungen/{vid}/dzn`
| ORGANISATOR, ADMINISTRATOR
| getStatus
| GET
| `/api/planungen/status`
| ORGANISATOR, ADMINISTRATOR
| importBundle
| POST
| `/api/planungen/{vid}/import`
| ORGANISATOR, ADMINISTRATOR
| startPlanung
| POST
| `/api/planungen/{vid}`
| ORGANISATOR, ADMINISTRATOR
|===

=== PrioritaetenResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getPrioritaeten
| GET
| `/api/prios/{vid}`
| TEILNEHMER, ORGANISATOR, ADMINISTRATOR
| updatePrioritaeten
| POST
| `/api/prios`
| TEILNEHMER, ORGANISATOR, ADMINISTRATOR
|===

=== ProtokollResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAllProtokollEntries
| GET
| `/api/organisator/protokolle`
| ORGANISATOR, ADMINISTRATOR
|===

=== ReferentResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| cloneTalkForEvent
| POST
| `/api/referenten/veranstaltungen/{targetEventId}/vortraege/{sourceVortragId}/clone`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| createVortrag
| POST
| `/api/referenten/vortraege`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| deleteVortrag
| DELETE
| `/api/referenten/vortraege/{vortragId}`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| getMyPlan
| GET
| `/api/referenten/plaene`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| getReferent
| GET
| `/api/referenten/profile`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| getReferentVeranstaltungen
| GET
| `/api/referenten/veranstaltungen`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| getReferentenVortraege
| GET
| `/api/referenten/vortraege`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| getVerfuegbarkeiten
| GET
| `/api/referenten/veranstaltungen/{vid}/verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| meldeVortragFuerVeranstaltungAb
| DELETE
| `/api/referenten/veranstaltungen/{eventId}/vortraege/{vortragId}/deregister`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| meldeVortragFuerVeranstaltungAn
| POST
| `/api/referenten/veranstaltungen/{eventId}/vortraege/{vortragId}/register`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| updateProfile
| PUT
| `/api/referenten/profile`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| updateVerfuegbarkeit
| POST
| `/api/referenten/veranstaltungen/{vid}/verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR, REFERENT
| updateVortrag
| PUT
| `/api/referenten/vortraege/{vortragId}`
| ORGANISATOR, ADMINISTRATOR, REFERENT
|===

=== ReportResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAbstimmungsfragebogenData
| GET
| `/api/reports/{vid}/abstimmungsfragebogen-data`
| ORGANISATOR, ADMINISTRATOR
| getAlleLaufzettelData
| GET
| `/api/reports/{vid}/laufzettel-alle-data`
| ORGANISATOR, ADMINISTRATOR
| getAlleLaufzettelReferentenData
| GET
| `/api/reports/{vid}/laufzettel-alle-referenten-data`
| ORGANISATOR, ADMINISTRATOR
| getAlleRaumschilderData
| GET
| `/api/reports/{vid}/raumschilder-data`
| ORGANISATOR, ADMINISTRATOR
| getFreieSlotsReferentenData
| GET
| `/api/reports/{vid}/freie-slots-referenten-data`
| ORGANISATOR, ADMINISTRATOR
| getFreieSlotsTeilnehmerData
| GET
| `/api/reports/{vid}/freie-slots-teilnehmer-data`
| ORGANISATOR, ADMINISTRATOR
| getLaufzettelReferentData
| GET
| `/api/reports/{vid}/referent/{rid}/laufzettel-data`
| REFERENT, ORGANISATOR, ADMINISTRATOR
| getLaufzettelTeilnehmerData
| GET
| `/api/reports/{vid}/teilnehmer/{tid}/laufzettel-data`
| TEILNEHMER, ORGANISATOR, ADMINISTRATOR
| getPriosDashboardData
| GET
| `/api/reports/{vid}/prios-dashboard-data`
| ORGANISATOR, ADMINISTRATOR
| getStundenplanData
| GET
| `/api/reports/{vid}/stundenplan-data`
| ORGANISATOR, ADMINISTRATOR
| getTeilnehmerDashboardData
| GET
| `/api/reports/{vid}/teilnehmer-dashboard-data`
| ORGANISATOR, ADMINISTRATOR, TEILNEHMER
| getUebersichtRaeumeData
| GET
| `/api/reports/{vid}/raeume-data`
| ORGANISATOR, ADMINISTRATOR
| getVortragAnmeldungenData
| GET
| `/api/reports/{vid}/vortrag/{vortragId}/anmeldungen-data`
| ORGANISATOR, ADMINISTRATOR
| getWahlvortraegeAnmeldungenUebersichtData
| GET
| `/api/reports/{vid}/wahlvortraege-anmeldungen-uebersicht-data`
| ORGANISATOR, ADMINISTRATOR
|===

=== SlotResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAll
| GET
| `/api/slots`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
|===

=== TeilnehmerResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| createTeilnehmer
| POST
| `/api/teilnehmer`
| ORGANISATOR, ADMINISTRATOR
| deleteTeilnehmer
| DELETE
| `/api/teilnehmer/{id}`
| ORGANISATOR, ADMINISTRATOR
| getAlleVeranstaltungsteilnehmer
| GET
| `/api/teilnehmer`
| ORGANISATOR, ADMINISTRATOR
| getMeineVortraege
| GET
| `/api/teilnehmer/veranstaltungen/{vid}/vortraege`
| TEILNEHMER
| getPlan
| GET
| `/api/teilnehmer/veranstaltungen/{vid}/zuweisungen`
| TEILNEHMER
| getTeilnehmer
| GET
| `/api/teilnehmer/{id}`
| ORGANISATOR, ADMINISTRATOR
| getTeilnehmerProfile
| GET
| `/api/teilnehmer/profile`
| TEILNEHMER
| getTeilnehmerVeranstaltungen
| GET
| `/api/teilnehmer/veranstaltungen`
| TEILNEHMER
| getVerfuegbarkeiten
| GET
| `/api/teilnehmer/veranstaltungen/{vid}/verfuegbarkeiten`
| TEILNEHMER
| toggleActive
| PATCH
| `/api/teilnehmer/{id}/toggle`
| ORGANISATOR, ADMINISTRATOR
| updateTeilnehmer
| PUT
| `/api/teilnehmer/{id}`
| ORGANISATOR, ADMINISTRATOR
| updateTeilnehmerProfile
| PUT
| `/api/teilnehmer/profile`
| TEILNEHMER
| updateVerfuegbarkeit
| POST
| `/api/teilnehmer/veranstaltungen/{vid}/verfuegbarkeiten`
| TEILNEHMER
|===

=== VeranstaltungImportResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| importDataset
| POST
| `/api/administrator/veranstaltung-import/datasets/{name}/import`
| ADMINISTRATOR
| importZip
| POST
| `/api/administrator/veranstaltung-import/upload`
| ADMINISTRATOR
| listDatasets
| GET
| `/api/administrator/veranstaltung-import/datasets`
| ADMINISTRATOR
|===

=== VeranstaltungResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| create
| POST
| `/api/veranstaltungen`
| ORGANISATOR, ADMINISTRATOR
| createNutzer
| POST
| `/api/veranstaltungen/{vid}/nutzer`
| ORGANISATOR, ADMINISTRATOR
| createSlot
| POST
| `/api/veranstaltungen/{vid}/slots`
| ORGANISATOR, ADMINISTRATOR
| createVortrag
| POST
| `/api/veranstaltungen/{vid}/vortraege`
| ORGANISATOR, ADMINISTRATOR
| delete
| DELETE
| `/api/veranstaltungen/{id}`
| ORGANISATOR, ADMINISTRATOR
| deleteNutzer
| DELETE
| `/api/veranstaltungen/{vid}/nutzer/{id}`
| ORGANISATOR, ADMINISTRATOR
| deleteSlot
| DELETE
| `/api/veranstaltungen/{vid}/slots/{id}`
| ORGANISATOR, ADMINISTRATOR
| deleteVortrag
| DELETE
| `/api/veranstaltungen/{vid}/vortraege/{id}`
| ORGANISATOR, ADMINISTRATOR
| getAktuelleZuweisungen
| GET
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/teilnehmer/{tid}/zuweisungen`
| ORGANISATOR, ADMINISTRATOR
| getAll
| GET
| `/api/veranstaltungen`
| ORGANISATOR, ADMINISTRATOR
| getDetaillierterPlan
| GET
| `/api/veranstaltungen/{vid}/plan/details`
| ORGANISATOR, ADMINISTRATOR
| getGesamtplan
| GET
| `/api/veranstaltungen/{vid}/plan`
| ORGANISATOR, ADMINISTRATOR
| getNutzer
| GET
| `/api/veranstaltungen/{vid}/nutzer`
| ORGANISATOR, ADMINISTRATOR
| getOne
| GET
| `/api/veranstaltungen/{vid}`
| ORGANISATOR, ADMINISTRATOR
| getPlanQualitaet
| GET
| `/api/veranstaltungen/{vid}/plan/qualitaet`
| ORGANISATOR, ADMINISTRATOR
| getRaumUmbuchungOptionen
| GET
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/vortraege/{wahlvortragId}/instanzen/{instanzIndex}/raum-optionen`
| ORGANISATOR, ADMINISTRATOR
| getRaumVerfuegbarkeiten
| GET
| `/api/veranstaltungen/{vid}/raum-verfuegbarkeiten`
| ORGANISATOR, ADMINISTRATOR
| getSlots
| GET
| `/api/veranstaltungen/{vid}/slots`
| ORGANISATOR, ADMINISTRATOR, TEILNEHMER, REFERENT
| getStats
| GET
| `/api/veranstaltungen/{vid}/stats`
| ORGANISATOR, ADMINISTRATOR
| getUmbuchungsOptionen
| GET
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/teilnehmer/{tid}/umbuchen-optionen`
| ORGANISATOR, ADMINISTRATOR
| getVeranstaltungsVortrag
| GET
| `/api/veranstaltungen/{vid}/vortraege/{tid}`
| ORGANISATOR, ADMINISTRATOR
| getVortraege
| GET
| `/api/veranstaltungen/{vid}/vortraege`
| ORGANISATOR, ADMINISTRATOR, TEILNEHMER, REFERENT
| getWahlvortragInstanzen
| GET
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/instanzen`
| ORGANISATOR, ADMINISTRATOR
| importReferenten
| POST
| `/api/veranstaltungen/{vid}/referenten/import`
| ORGANISATOR, ADMINISTRATOR
| importSlots
| POST
| `/api/veranstaltungen/{vid}/slots/import`
| ORGANISATOR, ADMINISTRATOR
| importVeranstaltungen
| POST
| `/api/veranstaltungen/import`
| ORGANISATOR, ADMINISTRATOR
| importVortraege
| POST
| `/api/veranstaltungen/{vid}/vortraege/import`
| ORGANISATOR, ADMINISTRATOR
| listePlanungsergebnisse
| GET
| `/api/veranstaltungen/{vid}/planungsergebnisse`
| ORGANISATOR, ADMINISTRATOR
| loescheErgebnis
| DELETE
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}`
| ORGANISATOR, ADMINISTRATOR
| publiziereErgebnis
| PUT
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/publizieren`
| ORGANISATOR, ADMINISTRATOR
| sendeNachricht
| POST
| `/api/veranstaltungen/{vid}/nachrichten`
| ORGANISATOR, ADMINISTRATOR
| teilnehmerNachbuchen
| POST
| `/api/veranstaltungen/{vid}/teilnehmer/{tid}/nachbuchen`
| ORGANISATOR, ADMINISTRATOR
| teilnehmerUmbuchen
| POST
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/teilnehmer/{tid}/umbuchen`
| ORGANISATOR, ADMINISTRATOR
| update
| PUT
| `/api/veranstaltungen/{id}`
| ORGANISATOR, ADMINISTRATOR
| updateNutzer
| PUT
| `/api/veranstaltungen/{vid}/nutzer/{id}`
| ORGANISATOR, ADMINISTRATOR
| updateSlot
| PUT
| `/api/veranstaltungen/{vid}/slots/{id}`
| ORGANISATOR, ADMINISTRATOR
| updateVortrag
| PUT
| `/api/veranstaltungen/{vid}/vortraege/{vortragId}`
| ORGANISATOR, ADMINISTRATOR
| uploadTeilnehmerCsv
| POST
| `/api/veranstaltungen/{vid}/teilnehmer/import`
| ORGANISATOR, ADMINISTRATOR
| vortragsInstanzRaumUmbuchen
| POST
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/raum-umbuchen`
| ORGANISATOR, ADMINISTRATOR
| vortragsInstanzUmplanen
| POST
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/umplanen`
| ORGANISATOR, ADMINISTRATOR
| zurueckziehenErgebnis
| PUT
| `/api/veranstaltungen/{vid}/planungsergebnisse/{ergebnisId}/zurueckziehen`
| ORGANISATOR, ADMINISTRATOR
|===

=== VerbesserungsvorschlagResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| create
| POST
| `/api/verbesserungsvorschlaege`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
| delete
| DELETE
| `/api/verbesserungsvorschlaege/{id}`
| ORGANISATOR, ADMINISTRATOR
| getAll
| GET
| `/api/verbesserungsvorschlaege`
| ORGANISATOR, ADMINISTRATOR
| updateStatus
| PUT
| `/api/verbesserungsvorschlaege/{id}/status`
| ORGANISATOR, ADMINISTRATOR
|===

=== WartungshinweisResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| get
| GET
| `/api/wartungshinweis`
| ORGANISATOR, ADMINISTRATOR, REFERENT, TEILNEHMER
| loeschen
| DELETE
| `/api/wartungshinweis`
| ADMINISTRATOR
| setzen
| PUT
| `/api/wartungshinweis`
| ADMINISTRATOR
|===

=== KalenderResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getOrganisatorKalender
| GET
| `/api/kalender/organisator/{veranstaltungId}`
| ORGANISATOR, ADMINISTRATOR
| getReferentKalender
| GET
| `/api/kalender/referent/{veranstaltungId}`
| REFERENT
| getTeilnehmerKalender
| GET
| `/api/kalender/teilnehmer/{veranstaltungId}`
| TEILNEHMER
|===

