= Automatisch generierte UseCase Dokumentation
:toc: left
:sectnums:

== UseCase Diagramm (PlantUML)

[plantuml, usecase-gen, svg]
----
@startuml
left to right direction
actor "ADMIN" as ADMIN
actor "PUBLIC" as PUBLIC
actor "REFERENT" as REFERENT
actor "TEILNEHMER" as TEILNEHMER
package "Vortragsmanager API" {
  (createTeilnehmer) as createTeilnehmer
  (updateTeilnehmer) as updateTeilnehmer
  (deleteTeilnehmer) as deleteTeilnehmer
  (getTeilnehmer) as getTeilnehmer
  (uploadCsv) as uploadCsv
  (toggleActive) as toggleActive
  (getAlleVeranstaltungsteilnehmer) as getAlleVeranstaltungsteilnehmer
  (getReferentVeranstaltungen) as getReferentVeranstaltungen
  (deregisterTalkFromEvent) as deregisterTalkFromEvent
  (getMeineVortraege) as getMeineVortraege
  (registerTalkForEvent) as registerTalkForEvent
  (getMyPlan) as getMyPlan
  (createVortrag) as createVortrag
  (updateVortrag) as updateVortrag
  (updateProfile) as updateProfile
  (getProfile) as getProfile
  (deleteVortrag) as deleteVortrag
  (getMyPriorities) as getMyPriorities
  (updateMyPriorities) as updateMyPriorities
  (getMeineVeranstaltungen) as getMeineVeranstaltungen
  (getPlan) as getPlan
  (getPrios) as getPrios
  (savePriorities) as savePriorities
  (getVortraege) as getVortraege
  (getVerfuegbarkeiten) as getVerfuegbarkeiten
  (updateVerfuegbarkeit) as updateVerfuegbarkeit
  (getAllUsers) as getAllUsers
  (createUser) as createUser
  (updateUser) as updateUser
  (inviteUser) as inviteUser
  (importAdmins) as importAdmins
  (deleteUser) as deleteUser
  (getDetaillierterPlan) as getDetaillierterPlan
  (getPlanQualitaet) as getPlanQualitaet
  (starteOptimierung) as starteOptimierung
  (importVeranstaltungen) as importVeranstaltungen
  (importReferenten) as importReferenten
  (uploadTeilnehmerCsv) as uploadTeilnehmerCsv
  (importVortraege) as importVortraege
  (getGesamtplan) as getGesamtplan
  (getNutzer) as getNutzer
  (createNutzer) as createNutzer
  (updateNutzer) as updateNutzer
  (deleteNutzer) as deleteNutzer
  (getSlots) as getSlots
  (createSlot) as createSlot
  (updateSlot) as updateSlot
  (deleteSlot) as deleteSlot
  (importSlots) as importSlots
  (getOne) as getOne
  (getStats) as getStats
  (update) as update
  (delete) as delete
  (create) as create
  (getAll) as getAll
  (getRaeumeByGebaeude) as getRaeumeByGebaeude
  (importGebaeude) as importGebaeude
  (createRaum) as createRaum
  (updateRaum) as updateRaum
  (deleteRaum) as deleteRaum
  (importRaeume) as importRaeume
  (forgotPassword) as forgotPassword
  (resetPassword) as resetPassword
  (login) as login
}
ADMIN --> createTeilnehmer
ADMIN --> updateTeilnehmer
ADMIN --> deleteTeilnehmer
ADMIN --> getTeilnehmer
ADMIN --> uploadCsv
ADMIN --> toggleActive
ADMIN --> getAlleVeranstaltungsteilnehmer
ADMIN --> getReferentVeranstaltungen
ADMIN --> deregisterTalkFromEvent
ADMIN --> getMeineVortraege
ADMIN --> registerTalkForEvent
ADMIN --> getMyPlan
ADMIN --> createVortrag
ADMIN --> updateVortrag
ADMIN --> updateProfile
ADMIN --> getProfile
ADMIN --> deleteVortrag
ADMIN --> getMeineVeranstaltungen
ADMIN --> getPlan
ADMIN --> getPrios
ADMIN --> savePriorities
ADMIN --> getVortraege
ADMIN --> getVerfuegbarkeiten
ADMIN --> updateVerfuegbarkeit
ADMIN --> getAllUsers
ADMIN --> createUser
ADMIN --> updateUser
ADMIN --> inviteUser
ADMIN --> importAdmins
ADMIN --> deleteUser
ADMIN --> getDetaillierterPlan
ADMIN --> getPlanQualitaet
ADMIN --> starteOptimierung
ADMIN --> importVeranstaltungen
ADMIN --> importReferenten
ADMIN --> uploadTeilnehmerCsv
ADMIN --> importVortraege
ADMIN --> getVortraege
ADMIN --> getGesamtplan
ADMIN --> getNutzer
ADMIN --> createNutzer
ADMIN --> updateNutzer
ADMIN --> deleteNutzer
ADMIN --> getSlots
ADMIN --> createSlot
ADMIN --> updateSlot
ADMIN --> deleteSlot
ADMIN --> importSlots
ADMIN --> getOne
ADMIN --> createVortrag
ADMIN --> updateVortrag
ADMIN --> getStats
ADMIN --> deleteVortrag
ADMIN --> update
ADMIN --> delete
ADMIN --> create
ADMIN --> getAll
ADMIN --> getRaeumeByGebaeude
ADMIN --> importGebaeude
ADMIN --> createRaum
ADMIN --> updateRaum
ADMIN --> deleteRaum
ADMIN --> importRaeume
ADMIN --> getOne
ADMIN --> update
ADMIN --> delete
ADMIN --> create
ADMIN --> getAll
ADMIN --> getAll
PUBLIC --> getMyPriorities
PUBLIC --> updateMyPriorities
PUBLIC --> forgotPassword
PUBLIC --> resetPassword
PUBLIC --> login
REFERENT --> getReferentVeranstaltungen
REFERENT --> deregisterTalkFromEvent
REFERENT --> getMeineVortraege
REFERENT --> registerTalkForEvent
REFERENT --> getMyPlan
REFERENT --> createVortrag
REFERENT --> updateVortrag
REFERENT --> updateProfile
REFERENT --> getProfile
REFERENT --> deleteVortrag
REFERENT --> getAll
TEILNEHMER --> getMeineVeranstaltungen
TEILNEHMER --> getPlan
TEILNEHMER --> getPrios
TEILNEHMER --> savePriorities
TEILNEHMER --> getVortraege
TEILNEHMER --> getAll
@enduml
----

== API Endpunkte & Rollen

=== TeilnehmerResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| createTeilnehmer
| POST
| `/api/admin/teilnehmer`
| ADMIN
| updateTeilnehmer
| PUT
| `/api/admin/teilnehmer/{id}`
| ADMIN
| deleteTeilnehmer
| DELETE
| `/api/admin/teilnehmer/{id}`
| ADMIN
| getTeilnehmer
| GET
| `/api/admin/teilnehmer/{id}`
| ADMIN
| uploadCsv
| POST
| `/api/admin/teilnehmer/import`
| ADMIN
| toggleActive
| PATCH
| `/api/admin/teilnehmer/{id}/toggle`
| ADMIN
| getAlleVeranstaltungsteilnehmer
| GET
| `/api/admin/teilnehmer`
| ADMIN
|===

=== ReferentResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getReferentVeranstaltungen
| GET
| `/api/referenten/veranstaltungen`
| ADMIN, REFERENT
| deregisterTalkFromEvent
| DELETE
| `/api/referenten/veranstaltungen/{eventId}/vortraege/{talkId}/deregister`
| ADMIN, REFERENT
| getMeineVortraege
| GET
| `/api/referenten/vortraege`
| ADMIN, REFERENT
| registerTalkForEvent
| POST
| `/api/referenten/veranstaltungen/{eventId}/vortraege/{talkId}/register`
| ADMIN, REFERENT
| getMyPlan
| GET
| `/api/referenten/plaene`
| ADMIN, REFERENT
| createVortrag
| POST
| `/api/referenten/vortraege`
| ADMIN, REFERENT
| updateVortrag
| PUT
| `/api/referenten/vortraege/{vortragId}`
| ADMIN, REFERENT
| updateProfile
| PUT
| `/api/referenten/profile`
| ADMIN, REFERENT
| getProfile
| GET
| `/api/referenten/profile`
| ADMIN, REFERENT
| deleteVortrag
| DELETE
| `/api/referenten/vortraege/{vortragId}`
| ADMIN, REFERENT
|===

=== TeilnehmerPrioritaetenResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getMyPriorities
| GET
| `/api/teilnehmer/priorities`
| PUBLIC
| updateMyPriorities
| POST
| `/api/teilnehmer/priorities`
| PUBLIC
|===

=== TeilnehmerPlanResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getMeineVeranstaltungen
| GET
| `/api/teilnehmer/veranstaltungen`
| TEILNEHMER, ADMIN
| getPlan
| GET
| `/api/teilnehmer/zuweisungen`
| TEILNEHMER, ADMIN
| getPrios
| GET
| `/api/teilnehmer/prios`
| TEILNEHMER, ADMIN
| savePriorities
| POST
| `/api/teilnehmer/prios`
| TEILNEHMER, ADMIN
| getVortraege
| GET
| `/api/teilnehmer/vortraege`
| TEILNEHMER, ADMIN
|===

=== AdminResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getVerfuegbarkeiten
| GET
| `/api/admin/veranstaltungen/{vid}/verfuegbarkeiten`
| ADMIN
| updateVerfuegbarkeit
| POST
| `/api/admin/veranstaltungen/{vid}/verfuegbarkeiten`
| ADMIN
| getAllUsers
| GET
| `/api/admin/nutzer`
| ADMIN
| createUser
| POST
| `/api/admin/nutzer`
| ADMIN
| updateUser
| PUT
| `/api/admin/nutzer/{id}`
| ADMIN
| inviteUser
| POST
| `/api/admin/nutzer/{userId}/einladen/{eventId}`
| ADMIN
| importAdmins
| POST
| `/api/admin/admins/import`
| ADMIN
| deleteUser
| DELETE
| `/api/admin/nutzer/{id}`
| ADMIN
|===

=== VeranstaltungResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getDetaillierterPlan
| GET
| `/api/veranstaltungen/{vid}/plan/details`
| ADMIN
| getPlanQualitaet
| GET
| `/api/veranstaltungen/{vid}/plan/qualitaet`
| ADMIN
| starteOptimierung
| POST
| `/api/veranstaltungen/{vid}/optimierung/start`
| ADMIN
| importVeranstaltungen
| POST
| `/api/veranstaltungen/import`
| ADMIN
| importReferenten
| POST
| `/api/veranstaltungen/{vid}/referenten/import`
| ADMIN
| uploadTeilnehmerCsv
| POST
| `/api/veranstaltungen/{vid}/teilnehmer/import`
| ADMIN
| importVortraege
| POST
| `/api/veranstaltungen/{vid}/vortraege/import`
| ADMIN
| getVortraege
| GET
| `/api/veranstaltungen/{vid}/vortraege`
| ADMIN
| getGesamtplan
| GET
| `/api/veranstaltungen/{vid}/plan`
| ADMIN
| getNutzer
| GET
| `/api/veranstaltungen/{vid}/nutzer`
| ADMIN
| createNutzer
| POST
| `/api/veranstaltungen/{vid}/nutzer`
| ADMIN
| updateNutzer
| PUT
| `/api/veranstaltungen/{vid}/nutzer/{id}`
| ADMIN
| deleteNutzer
| DELETE
| `/api/veranstaltungen/{vid}/nutzer/{id}`
| ADMIN
| getSlots
| GET
| `/api/veranstaltungen/{vid}/slots`
| ADMIN
| createSlot
| POST
| `/api/veranstaltungen/{vid}/slots`
| ADMIN
| updateSlot
| PUT
| `/api/veranstaltungen/{vid}/slots/{id}`
| ADMIN
| deleteSlot
| DELETE
| `/api/veranstaltungen/{vid}/slots/{id}`
| ADMIN
| importSlots
| POST
| `/api/veranstaltungen/{vid}/slots/import`
| ADMIN
| getOne
| GET
| `/api/veranstaltungen/{vid}`
| ADMIN
| createVortrag
| POST
| `/api/veranstaltungen/{vid}/vortraege`
| ADMIN
| updateVortrag
| PUT
| `/api/veranstaltungen/{vid}/vortraege/{id}`
| ADMIN
| getStats
| GET
| `/api/veranstaltungen/{vid}/stats`
| ADMIN
| deleteVortrag
| DELETE
| `/api/veranstaltungen/{vid}/vortraege/{id}`
| ADMIN
| update
| PUT
| `/api/veranstaltungen/{id}`
| ADMIN
| delete
| DELETE
| `/api/veranstaltungen/{id}`
| ADMIN
| create
| POST
| `/api/veranstaltungen`
| ADMIN
| getAll
| GET
| `/api/veranstaltungen`
| ADMIN
|===

=== GebaeudeResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getRaeumeByGebaeude
| GET
| `/api/gebaeude/{gid}/raeume`
| ADMIN
| importGebaeude
| POST
| `/api/gebaeude/import`
| ADMIN
| createRaum
| POST
| `/api/gebaeude/{gid}/raeume`
| ADMIN
| updateRaum
| PUT
| `/api/gebaeude/{gid}/raeume/{rid}`
| ADMIN
| deleteRaum
| DELETE
| `/api/gebaeude/{gid}/raeume/{rid}`
| ADMIN
| importRaeume
| POST
| `/api/gebaeude/{gid}/raeume/import`
| ADMIN
| getOne
| GET
| `/api/gebaeude/{id}`
| ADMIN
| update
| PUT
| `/api/gebaeude/{id}`
| ADMIN
| delete
| DELETE
| `/api/gebaeude/{id}`
| ADMIN
| create
| POST
| `/api/gebaeude`
| ADMIN
| getAll
| GET
| `/api/gebaeude`
| ADMIN
|===

=== SlotResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAll
| GET
| `/api/slots`
| ADMIN, REFERENT, TEILNEHMER
|===

=== AuthResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| forgotPassword
| POST
| `/api/auth/forgot-password`
| PUBLIC
| resetPassword
| POST
| `/api/auth/reset-password`
| PUBLIC
| login
| POST
| `/api/auth/login`
| PUBLIC
|===

