= Automatisch generierte UseCase Dokumentation
:toc: left
:sectnums:

== UseCase Diagramm (PlantUML)

[plantuml, usecase-gen, svg]
----
@startuml
left to right direction
actor "ADMIN" as ADMIN
actor "REFERENT" as REFERENT
actor "TEILNEHMER" as TEILNEHMER
package "KonfPlan API" {
  (deleteUser) as deleteUser
  (getAllUsers) as getAllUsers
  (updateUser) as updateUser
  (createGruppe) as createGruppe
  (renameGruppe) as renameGruppe
  (deleteGruppe) as deleteGruppe
  (ocreateUser) as ocreateUser
  (getUser) as getUser
  (inviteUser) as inviteUser
  (importAdmins) as importAdmins
  (getGruppen) as getGruppen
  (getVerfuegbarkeiten) as getVerfuegbarkeiten
  (updateVerfuegbarkeit) as updateVerfuegbarkeit
  (importPrioritaeten) as importPrioritaeten
  (getRaumVerfuegbarkeiten) as getRaumVerfuegbarkeiten
  (updateRaumVerfuegbarkeit) as updateRaumVerfuegbarkeit
  (updateTeilnehmerPrioritaet) as updateTeilnehmerPrioritaet
  (update) as update
  (delete) as delete
  (create) as create
  (getAll) as getAll
  (importGebaeude) as importGebaeude
  (createRaum) as createRaum
  (updateRaum) as updateRaum
  (deleteRaum) as deleteRaum
  (importRaeume) as importRaeume
  (getOne) as getOne
  (getRaeumeByGebaeude) as getRaeumeByGebaeude
  (getAllProtokollEntries) as getAllProtokollEntries
  (updateProfile) as updateProfile
  (createVortrag) as createVortrag
  (updateVortrag) as updateVortrag
  (deleteVortrag) as deleteVortrag
  (getMyPlan) as getMyPlan
  (getReferent) as getReferent
  (cloneTalkForEvent) as cloneTalkForEvent
  (getReferentenVortraege) as getReferentenVortraege
  (registerTalkForEvent) as registerTalkForEvent
  (getReferentVeranstaltungen) as getReferentVeranstaltungen
  (deregisterTalkFromEvent) as deregisterTalkFromEvent
  (getRaumbelegungsplan) as getRaumbelegungsplan
  (getLaufzettelReferent) as getLaufzettelReferent
  (getUebersichtRaeume) as getUebersichtRaeume
  (getUebersichtRaeumePdf) as getUebersichtRaeumePdf
  (getFreieSlotsReferenten) as getFreieSlotsReferenten
  (getFreieSlotsTeilnehmer) as getFreieSlotsTeilnehmer
  (getLaufzettelTeilnehmer) as getLaufzettelTeilnehmer
  (getLaufzettelTeilnehmerPdf) as getLaufzettelTeilnehmerPdf
  (getLaufzettelReferentPdf) as getLaufzettelReferentPdf
  (getRaumbelegungsplanPdf) as getRaumbelegungsplanPdf
  (getFreieSlotsReferentenPdf) as getFreieSlotsReferentenPdf
  (getFreieSlotsTeilnehmerPdf) as getFreieSlotsTeilnehmerPdf
  (getPlan) as getPlan
  (getPrios) as getPrios
  (savePriorities) as savePriorities
  (getMeineVeranstaltungen) as getMeineVeranstaltungen
  (getPrioritaeten) as getPrioritaeten
  (updatePrioritaeten) as updatePrioritaeten
  (toggleActive) as toggleActive
  (uploadCsv) as uploadCsv
  (getTeilnehmer) as getTeilnehmer
  (createTeilnehmer) as createTeilnehmer
  (updateTeilnehmer) as updateTeilnehmer
  (getTeilnehmerProfile) as getTeilnehmerProfile
  (deleteTeilnehmer) as deleteTeilnehmer
  (getAlleVeranstaltungsteilnehmer) as getAlleVeranstaltungsteilnehmer
  (updateTeilnehmerProfile) as updateTeilnehmerProfile
  (getSlots) as getSlots
  (createSlot) as createSlot
  (updateSlot) as updateSlot
  (deleteSlot) as deleteSlot
  (getGesamtplan) as getGesamtplan
  (createNutzer) as createNutzer
  (updateNutzer) as updateNutzer
  (deleteNutzer) as deleteNutzer
  (importSlots) as importSlots
  (getVortraege) as getVortraege
  (getNutzer) as getNutzer
  (getStats) as getStats
  (getDetaillierterPlan) as getDetaillierterPlan
  (getPlanQualitaet) as getPlanQualitaet
  (startePlanErstellung) as startePlanErstellung
  (importVeranstaltungen) as importVeranstaltungen
  (importReferenten) as importReferenten
  (uploadTeilnehmerCsv) as uploadTeilnehmerCsv
  (importVortraege) as importVortraege
  (getVeranstaltungsVortrag) as getVeranstaltungsVortrag
  (saveTeilnehmerPrioritaeten) as saveTeilnehmerPrioritaeten
}
ADMIN --> deleteUser
ADMIN --> getAllUsers
ADMIN --> updateUser
ADMIN --> createGruppe
ADMIN --> renameGruppe
ADMIN --> deleteGruppe
ADMIN --> ocreateUser
ADMIN --> getUser
ADMIN --> inviteUser
ADMIN --> importAdmins
ADMIN --> getGruppen
ADMIN --> getVerfuegbarkeiten
ADMIN --> updateVerfuegbarkeit
ADMIN --> importPrioritaeten
ADMIN --> getRaumVerfuegbarkeiten
ADMIN --> updateRaumVerfuegbarkeit
ADMIN --> updateTeilnehmerPrioritaet
ADMIN --> update
ADMIN --> delete
ADMIN --> create
ADMIN --> getAll
ADMIN --> importGebaeude
ADMIN --> createRaum
ADMIN --> updateRaum
ADMIN --> deleteRaum
ADMIN --> importRaeume
ADMIN --> getOne
ADMIN --> getRaeumeByGebaeude
ADMIN --> getAllProtokollEntries
ADMIN --> updateProfile
ADMIN --> createVortrag
ADMIN --> updateVortrag
ADMIN --> deleteVortrag
ADMIN --> getMyPlan
ADMIN --> getReferent
ADMIN --> cloneTalkForEvent
ADMIN --> getReferentenVortraege
ADMIN --> registerTalkForEvent
ADMIN --> getVerfuegbarkeiten
ADMIN --> updateVerfuegbarkeit
ADMIN --> getReferentVeranstaltungen
ADMIN --> deregisterTalkFromEvent
ADMIN --> getRaumbelegungsplan
ADMIN --> getLaufzettelReferent
ADMIN --> getUebersichtRaeume
ADMIN --> getUebersichtRaeumePdf
ADMIN --> getFreieSlotsReferenten
ADMIN --> getFreieSlotsTeilnehmer
ADMIN --> getLaufzettelTeilnehmer
ADMIN --> getLaufzettelTeilnehmerPdf
ADMIN --> getLaufzettelReferentPdf
ADMIN --> getRaumbelegungsplanPdf
ADMIN --> getFreieSlotsReferentenPdf
ADMIN --> getFreieSlotsTeilnehmerPdf
ADMIN --> getAll
ADMIN --> getPlan
ADMIN --> getPrios
ADMIN --> savePriorities
ADMIN --> getVerfuegbarkeiten
ADMIN --> updateVerfuegbarkeit
ADMIN --> getMeineVeranstaltungen
ADMIN --> toggleActive
ADMIN --> uploadCsv
ADMIN --> getTeilnehmer
ADMIN --> createTeilnehmer
ADMIN --> updateTeilnehmer
ADMIN --> deleteTeilnehmer
ADMIN --> getAlleVeranstaltungsteilnehmer
ADMIN --> update
ADMIN --> delete
ADMIN --> create
ADMIN --> getAll
ADMIN --> createVortrag
ADMIN --> updateVortrag
ADMIN --> deleteVortrag
ADMIN --> getSlots
ADMIN --> createSlot
ADMIN --> updateSlot
ADMIN --> deleteSlot
ADMIN --> getGesamtplan
ADMIN --> createNutzer
ADMIN --> updateNutzer
ADMIN --> deleteNutzer
ADMIN --> importSlots
ADMIN --> getVortraege
ADMIN --> getNutzer
ADMIN --> getStats
ADMIN --> getOne
ADMIN --> getDetaillierterPlan
ADMIN --> getPlanQualitaet
ADMIN --> startePlanErstellung
ADMIN --> importVeranstaltungen
ADMIN --> importReferenten
ADMIN --> uploadTeilnehmerCsv
ADMIN --> importVortraege
ADMIN --> getRaumVerfuegbarkeiten
ADMIN --> getVeranstaltungsVortrag
ADMIN --> saveTeilnehmerPrioritaeten
REFERENT --> updateProfile
REFERENT --> createVortrag
REFERENT --> updateVortrag
REFERENT --> deleteVortrag
REFERENT --> getMyPlan
REFERENT --> getReferent
REFERENT --> cloneTalkForEvent
REFERENT --> getReferentenVortraege
REFERENT --> registerTalkForEvent
REFERENT --> getVerfuegbarkeiten
REFERENT --> updateVerfuegbarkeit
REFERENT --> getReferentVeranstaltungen
REFERENT --> deregisterTalkFromEvent
REFERENT --> getLaufzettelReferent
REFERENT --> getLaufzettelReferentPdf
REFERENT --> getAll
REFERENT --> getSlots
TEILNEHMER --> getLaufzettelTeilnehmer
TEILNEHMER --> getLaufzettelTeilnehmerPdf
TEILNEHMER --> getAll
TEILNEHMER --> getPlan
TEILNEHMER --> getPrios
TEILNEHMER --> savePriorities
TEILNEHMER --> getVerfuegbarkeiten
TEILNEHMER --> updateVerfuegbarkeit
TEILNEHMER --> getMeineVeranstaltungen
TEILNEHMER --> getPrioritaeten
TEILNEHMER --> updatePrioritaeten
TEILNEHMER --> getTeilnehmerProfile
TEILNEHMER --> updateTeilnehmerProfile
TEILNEHMER --> getSlots
TEILNEHMER --> getVortraege
@enduml
----

== API Endpunkte & Rollen

=== AdminResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| deleteUser
| DELETE
| `/api/admin/nutzer/{id}`
| ADMIN
| getAllUsers
| GET
| `/api/admin/nutzer`
| ADMIN
| updateUser
| PUT
| `/api/admin/nutzer/{id}`
| ADMIN
| createGruppe
| POST
| `/api/admin/veranstaltungen/{vid}/gruppen`
| ADMIN
| renameGruppe
| PUT
| `/api/admin/veranstaltungen/{vid}/gruppen`
| ADMIN
| deleteGruppe
| DELETE
| `/api/admin/veranstaltungen/{vid}/gruppen/{gruppenName}`
| ADMIN
| ocreateUser
| POST
| `/api/admin/nutzer`
| ADMIN
| getUser
| GET
| `/api/admin/nutzer/{id}`
| ADMIN
| inviteUser
| POST
| `/api/admin/nutzer/{userId}/einladen/{eventId}`
| ADMIN
| importAdmins
| POST
| `/api/admin/admins/import`
| ADMIN
| getGruppen
| GET
| `/api/admin/veranstaltungen/{vid}/gruppen`
| ADMIN
| getVerfuegbarkeiten
| GET
| `/api/admin/veranstaltungen/{vid}/verfuegbarkeiten`
| ADMIN
| updateVerfuegbarkeit
| POST
| `/api/admin/veranstaltungen/{vid}/verfuegbarkeiten`
| ADMIN
| importPrioritaeten
| POST
| `/api/admin/veranstaltungen/{vid}/prioritaeten/import`
| ADMIN
| getRaumVerfuegbarkeiten
| GET
| `/api/admin/veranstaltungen/{vid}/raeume/verfuegbarkeiten`
| ADMIN
| updateRaumVerfuegbarkeit
| POST
| `/api/admin/veranstaltungen/{vid}/raeume/verfuegbarkeiten`
| ADMIN
| updateTeilnehmerPrioritaet
| PUT
| `/api/admin/veranstaltungen/{vid}/teilnehmer/{tid}/priorities`
| ADMIN
|===

=== GebaeudeResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| update
| PUT
| `/api/gebaeude/{id}`
| ADMIN
| delete
| DELETE
| `/api/gebaeude/{id}`
| ADMIN
| create
| POST
| `/api/gebaeude`
| ADMIN
| getAll
| GET
| `/api/gebaeude`
| ADMIN
| importGebaeude
| POST
| `/api/gebaeude/import`
| ADMIN
| createRaum
| POST
| `/api/gebaeude/{gid}/raeume`
| ADMIN
| updateRaum
| PUT
| `/api/gebaeude/{gid}/raeume/{rid}`
| ADMIN
| deleteRaum
| DELETE
| `/api/gebaeude/{gid}/raeume/{rid}`
| ADMIN
| importRaeume
| POST
| `/api/gebaeude/{gid}/raeume/import`
| ADMIN
| getOne
| GET
| `/api/gebaeude/{id}`
| ADMIN
| getRaeumeByGebaeude
| GET
| `/api/gebaeude/{gid}/raeume`
| ADMIN
|===

=== ProtokollResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAllProtokollEntries
| GET
| `/api/admin/protokolle`
| ADMIN
|===

=== ReferentResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| updateProfile
| PUT
| `/api/referenten/profile`
| ADMIN, REFERENT
| createVortrag
| POST
| `/api/referenten/vortraege`
| ADMIN, REFERENT
| updateVortrag
| PUT
| `/api/referenten/vortraege/{vortragId}`
| ADMIN, REFERENT
| deleteVortrag
| DELETE
| `/api/referenten/vortraege/{vortragId}`
| ADMIN, REFERENT
| getMyPlan
| GET
| `/api/referenten/plaene`
| ADMIN, REFERENT
| getReferent
| GET
| `/api/referenten/profile`
| ADMIN, REFERENT
| cloneTalkForEvent
| POST
| `/api/referenten/veranstaltungen/{targetEventId}/vortraege/{sourceVortragId}/clone`
| ADMIN, REFERENT
| getReferentenVortraege
| GET
| `/api/referenten/vortraege`
| ADMIN, REFERENT
| registerTalkForEvent
| POST
| `/api/referenten/veranstaltungen/{eventId}/vortraege/{vortragId}/register`
| ADMIN, REFERENT
| getVerfuegbarkeiten
| GET
| `/api/referenten/veranstaltungen/{vid}/verfuegbarkeiten`
| ADMIN, REFERENT
| updateVerfuegbarkeit
| POST
| `/api/referenten/veranstaltungen/{vid}/verfuegbarkeiten`
| ADMIN, REFERENT
| getReferentVeranstaltungen
| GET
| `/api/referenten/veranstaltungen`
| ADMIN, REFERENT
| deregisterTalkFromEvent
| DELETE
| `/api/referenten/veranstaltungen/{eventId}/vortraege/{vortragId}/deregister`
| ADMIN, REFERENT
|===

=== ReportResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getRaumbelegungsplan
| GET
| `/api/reports/{vid}/raum/{rid}/belegungsplan`
| ADMIN
| getLaufzettelReferent
| GET
| `/api/reports/{vid}/referent/{rid}/laufzettel`
| REFERENT, ADMIN
| getUebersichtRaeume
| GET
| `/api/reports/{vid}/raeume`
| ADMIN
| getUebersichtRaeumePdf
| GET
| `/api/reports/{vid}/raeume-pdf`
| ADMIN
| getFreieSlotsReferenten
| GET
| `/api/reports/{vid}/freie-slots-referenten`
| ADMIN
| getFreieSlotsTeilnehmer
| GET
| `/api/reports/{vid}/freie-slots-teilnehmer`
| ADMIN
| getLaufzettelTeilnehmer
| GET
| `/api/reports/{vid}/teilnehmer/{tid}/laufzettel`
| TEILNEHMER, ADMIN
| getLaufzettelTeilnehmerPdf
| GET
| `/api/reports/{vid}/teilnehmer/{tid}/laufzettel-pdf`
| TEILNEHMER, ADMIN
| getLaufzettelReferentPdf
| GET
| `/api/reports/{vid}/referent/{rid}/laufzettel-pdf`
| REFERENT, ADMIN
| getRaumbelegungsplanPdf
| GET
| `/api/reports/{vid}/raum/{rid}/belegungsplan-pdf`
| ADMIN
| getFreieSlotsReferentenPdf
| GET
| `/api/reports/{vid}/freie-slots-referenten-pdf`
| ADMIN
| getFreieSlotsTeilnehmerPdf
| GET
| `/api/reports/{vid}/freie-slots-teilnehmer-pdf`
| ADMIN
|===

=== SlotResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getAll
| GET
| `/api/slots`
| ADMIN, REFERENT, TEILNEHMER
|===

=== TeilnehmerPlanResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getPlan
| GET
| `/api/teilnehmer/veranstaltungen/{vid}/zuweisungen`
| TEILNEHMER, ADMIN
| getPrios
| GET
| `/api/prios/{vid}`
| TEILNEHMER, ADMIN
| savePriorities
| POST
| `/api/prios`
| TEILNEHMER, ADMIN
| getVerfuegbarkeiten
| GET
| `/api/teilnehmer/veranstaltungen/{vid}/verfuegbarkeiten`
| TEILNEHMER, ADMIN
| updateVerfuegbarkeit
| POST
| `/api/teilnehmer/veranstaltungen/{vid}/verfuegbarkeiten`
| TEILNEHMER, ADMIN
| getMeineVeranstaltungen
| GET
| `/api/teilnehmer/veranstaltungen`
| TEILNEHMER, ADMIN
|===

=== TeilnehmerPrioritaetenResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| getPrioritaeten
| GET
| `/api/teilnehmer/veranstaltungen/{vid}/prios`
| TEILNEHMER
| updatePrioritaeten
| POST
| `/api/teilnehmer/veranstaltungen/{vid}/prios`
| TEILNEHMER
|===

=== TeilnehmerResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| toggleActive
| PATCH
| `/api/teilnehmer/{id}/toggle`
| ADMIN
| uploadCsv
| POST
| `/api/teilnehmer/import`
| ADMIN
| getTeilnehmer
| GET
| `/api/teilnehmer/{id}`
| ADMIN
| createTeilnehmer
| POST
| `/api/teilnehmer`
| ADMIN
| updateTeilnehmer
| PUT
| `/api/teilnehmer/{id}`
| ADMIN
| getTeilnehmerProfile
| GET
| `/api/teilnehmer/profile`
| TEILNEHMER
| deleteTeilnehmer
| DELETE
| `/api/teilnehmer/{id}`
| ADMIN
| getAlleVeranstaltungsteilnehmer
| GET
| `/api/teilnehmer`
| ADMIN
| updateTeilnehmerProfile
| PUT
| `/api/teilnehmer/profile`
| TEILNEHMER
|===

=== VeranstaltungResource

[cols="2,1,3,2", options="header"]
|===
| Aktion | Method | Pfad | Rollen
| update
| PUT
| `/api/veranstaltungen/{id}`
| ADMIN
| delete
| DELETE
| `/api/veranstaltungen/{id}`
| ADMIN
| create
| POST
| `/api/veranstaltungen`
| ADMIN
| getAll
| GET
| `/api/veranstaltungen`
| ADMIN
| createVortrag
| POST
| `/api/veranstaltungen/{vid}/vortraege`
| ADMIN
| updateVortrag
| PUT
| `/api/veranstaltungen/{vid}/vortraege/{vortragId}`
| ADMIN
| deleteVortrag
| DELETE
| `/api/veranstaltungen/{vid}/vortraege/{id}`
| ADMIN
| getSlots
| GET
| `/api/veranstaltungen/{vid}/slots`
| ADMIN, TEILNEHMER, REFERENT
| createSlot
| POST
| `/api/veranstaltungen/{vid}/slots`
| ADMIN
| updateSlot
| PUT
| `/api/veranstaltungen/{vid}/slots/{id}`
| ADMIN
| deleteSlot
| DELETE
| `/api/veranstaltungen/{vid}/slots/{id}`
| ADMIN
| getGesamtplan
| GET
| `/api/veranstaltungen/{vid}/plan`
| ADMIN
| createNutzer
| POST
| `/api/veranstaltungen/{vid}/nutzer`
| ADMIN
| updateNutzer
| PUT
| `/api/veranstaltungen/{vid}/nutzer/{id}`
| ADMIN
| deleteNutzer
| DELETE
| `/api/veranstaltungen/{vid}/nutzer/{id}`
| ADMIN
| importSlots
| POST
| `/api/veranstaltungen/{vid}/slots/import`
| ADMIN
| getVortraege
| GET
| `/api/veranstaltungen/{vid}/vortraege`
| ADMIN, TEILNEHMER
| getNutzer
| GET
| `/api/veranstaltungen/{vid}/nutzer`
| ADMIN
| getStats
| GET
| `/api/veranstaltungen/{vid}/stats`
| ADMIN
| getOne
| GET
| `/api/veranstaltungen/{vid}`
| ADMIN
| getDetaillierterPlan
| GET
| `/api/veranstaltungen/{vid}/plan/details`
| ADMIN
| getPlanQualitaet
| GET
| `/api/veranstaltungen/{vid}/plan/qualitaet`
| ADMIN
| startePlanErstellung
| POST
| `/api/veranstaltungen/{vid}/planungen`
| ADMIN
| importVeranstaltungen
| POST
| `/api/veranstaltungen/import`
| ADMIN
| importReferenten
| POST
| `/api/veranstaltungen/{vid}/referenten/import`
| ADMIN
| uploadTeilnehmerCsv
| POST
| `/api/veranstaltungen/{vid}/teilnehmer/import`
| ADMIN
| importVortraege
| POST
| `/api/veranstaltungen/{vid}/vortraege/import`
| ADMIN
| getRaumVerfuegbarkeiten
| GET
| `/api/veranstaltungen/{vid}/raum-verfuegbarkeiten`
| ADMIN
| getVeranstaltungsVortrag
| GET
| `/api/veranstaltungen/{vid}/vortraege/{tid}`
| ADMIN
| saveTeilnehmerPrioritaeten
| PUT
| `/api/veranstaltungen/{vid}/teilnehmer/{userId}/prioritaeten`
| ADMIN
|===

