####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# Before building the container image run:
#
# ./mvnw package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/quarkus-postgres-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/quarkus-postgres-jvm
#
# If you want to include the debug port into your docker image
# you will have to expose the debug port (default 5005 being the default) like this :  EXPOSE 8080 5005.
# Additionally you will have to set -e JAVA_DEBUG=true and -e JAVA_DEBUG_PORT=*:5005
# when running the container
#
# Then run the container using :
#
# docker run -i --rm -p 8080:8080 quarkus/quarkus-postgres-jvm
#
# This image uses the `run-java.sh` script to run the application.
# This scripts computes the command line to execute your Java application, and
# includes memory/GC tuning.
# You can configure the behavior using the following environment properties:
# - JAVA_OPTS: JVM options passed to the `java` command (example: "-verbose:class")
# - JAVA_OPTS_APPEND: User specified Java options to be appended to generated options
#   in JAVA_OPTS (example: "-Dsome.property=foo")
# - JAVA_MAX_MEM_RATIO: Is used when no `-Xmx` option is given in JAVA_OPTS. This is
#   used to calculate a default maximal heap memory based on a containers restriction.
#   If used in a container without any memory constraints for the container then this
#   option has no effect. If there is a memory constraint then `-Xmx` is set to a ratio
#   of the container available memory as set here. The default is `50` which means 50%
#   of the available memory is used as an upper boundary. You can skip this mechanism by
#   setting this value to `0` in which case no `-Xmx` option is added.
# - JAVA_INITIAL_MEM_RATIO: Is used when no `-Xms` option is given in JAVA_OPTS. This
#   is used to calculate a default initial heap memory based on the maximum heap memory.
#   If used in a container without any memory constraints for the container then this
#   option has no effect. If there is a memory constraint then `-Xms` is set to a ratio
#   of the `-Xmx` memory as set here. The default is `25` which means 25% of the `-Xmx`
#   is used as the initial heap size. You can skip this mechanism by setting this value
#   to `0` in which case no `-Xms` option is added (example: "25")
# - JAVA_MAX_INITIAL_MEM: Is used when no `-Xms` option is given in JAVA_OPTS.
#   This is used to calculate the maximum value of the initial heap memory. If used in
#   a container without any memory constraints for the container then this option has
#   no effect. If there is a memory constraint then `-Xms` is limited to the value set
#   here. The default is 4096MB which means the calculated value of `-Xms` never will
#   be greater than 4096MB. The value of this variable is expressed in MB (example: "4096")
# - JAVA_DIAGNOSTICS: Set this to get some diagnostics information to standard output
#   when things are happening. This option, if set to true, will set
#  `-XX:+UnlockDiagnosticVMOptions`. Disabled by default (example: "true").
# - JAVA_DEBUG: If set remote debugging will be switched on. Disabled by default (example:
#    true").
# - JAVA_DEBUG_PORT: Port used for remote debugging. Defaults to 5005 (example: "8787").
# - CONTAINER_CORE_LIMIT: A calculated core limit as described in
#   https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt. (example: "2")
# - CONTAINER_MAX_MEMORY: Memory limit given to the container (example: "1024").
# - GC_MIN_HEAP_FREE_RATIO: Minimum percentage of heap free after GC to avoid expansion.
#   (example: "20")
# - GC_MAX_HEAP_FREE_RATIO: Maximum percentage of heap free after GC to avoid shrinking.
#   (example: "40")
# - GC_TIME_RATIO: Specifies the ratio of the time spent outside the garbage collection.
#   (example: "4")
# - GC_ADAPTIVE_SIZE_POLICY_WEIGHT: The weighting given to the current GC time versus
#   previous GC times. (example: "90")
# - GC_METASPACE_SIZE: The initial metaspace size. (example: "20")
# - GC_MAX_METASPACE_SIZE: The maximum metaspace size. (example: "100")
# - GC_CONTAINER_OPTIONS: Specify Java GC to use. The value of this variable should
#   contain the necessary JRE command-line options to specify the required GC, which
#   will override the default of `-XX:+UseParallelGC` (example: -XX:+UseG1GC).
# - HTTPS_PROXY: The location of the https proxy. (example: "myuser@127.0.0.1:8080")
# - HTTP_PROXY: The location of the http proxy. (example: "myuser@127.0.0.1:8080")
# - NO_PROXY: A comma separated lists of hosts, IP addresses or domains that can be
#   accessed directly. (example: "foo.example.com,bar.example.com")
#
###
FROM registry.access.redhat.com/ubi8/openjdk-21:1.21

ENV LANGUAGE='en_US:en'

# MiniZinc wird von PlanErstellungService als externer Prozess ueber einen
# absoluten Pfad aufgerufen (kein PATH-Lookup) - daher hier fest ins Image
# installieren, damit der Container eigenstaendig lauffaehig ist.
USER root
RUN microdnf install -y gzip tar && microdnf clean all
RUN curl -fsSL https://api.github.com/repos/MiniZinc/MiniZincIDE/releases/latest \
        | grep -o '"browser_download_url": *"[^"]*x86_64-linux-gnu\.tgz"' \
        | head -1 | cut -d '"' -f4 > /tmp/minizinc-url \
    && curl -fsSL -o /tmp/minizinc.tgz "$(cat /tmp/minizinc-url)" \
    && mkdir -p /opt/minizinc \
    && tar -xzf /tmp/minizinc.tgz -C /opt/minizinc --strip-components=1 \
    && rm -f /tmp/minizinc.tgz /tmp/minizinc-url \
    && chown -R 185:0 /opt/minizinc
ENV MINIZINC_PATH="/opt/minizinc/bin/minizinc"

# pg_dump wird von DatabaseBackupService als externer Prozess aufgerufen (Administrator-Export,
# siehe application.properties "pg-dump.path"). UBI8s eigenes microdnf-Repo fuehrt nur veraltete
# Postgres-Client-Versionen - pg_dump darf aber nicht aelter sein als der gesicherte Server
# (Postgres 18, siehe deploy/docker-compose.yml), sonst schlaegt der Dump fehl oder ist
# unvollstaendig. Daher stattdessen ueber das offizielle PGDG-Repo installieren, das gezielt
# "postgresql18" (nur Client-Tools, kein Server) fuer EL8 bereitstellt. Das Repo-RPM selbst
# NICHT per "microdnf install <url>" installieren - anders als dnf/yum akzeptiert microdnf keine
# Remote-URL als Paketquelle ("error: No package matches <url>", live in CI beobachtet) - daher
# die Repo-Definition direkt schreiben (kein GPG-Check noetig, da HTTPS + offizielle
# PostgreSQL-Domain, analog zum unsignierten MiniZinc-Download oben).
RUN printf '[pgdg18]\nname=PostgreSQL 18 for RHEL 8 - x86_64\nbaseurl=https://download.postgresql.org/pub/repos/yum/18/redhat/rhel-8-x86_64\nenabled=1\ngpgcheck=0\n' > /etc/yum.repos.d/pgdg18.repo \
    && microdnf install -y postgresql18 \
    && microdnf clean all
ENV PG_DUMP_PATH="/usr/pgsql-18/bin/pg_dump"

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]

