#!/bin/sh
set -e

case "$1" in
    remove)
        systemctl stop konfplan.service || true
        systemctl daemon-reload || true
        ;;
    purge)
        systemctl disable konfplan.service || true
        deluser --system konfplan || true
        rm -rf /var/lib/konfplan
        ;;
esac

exit 0
