package kreyj.konfplan.persistence;

public enum NachrichtKategorie {
    VORTRAG_ZURUECKGEZOGEN,
    ORGANISATOR_NACHRICHT,
    VORTRAG_AUSGEFALLEN,
    TEILNEHMER_UMGEBUCHT,
    TEILNEHMER_NICHT_VERFUEGBAR,
    TEILNEHMER_NACHGEBUCHT
}
