-- Flyway Migration für PostgreSQL / H2
DROP TABLE IF EXISTS Veranstaltung_Gebaeude CASCADE;
DROP TABLE IF EXISTS User_Veranstaltung CASCADE;
DROP TABLE IF EXISTS Zuweisung CASCADE;
DROP TABLE IF EXISTS Wahlvortrag_EventSlot CASCADE;
DROP TABLE IF EXISTS Verfuegbarkeit CASCADE;
DROP TABLE IF EXISTS Prioritaet CASCADE;
DROP TABLE IF EXISTS Vortrag CASCADE;
DROP TABLE IF EXISTS Teilnehmer_EventSlot CASCADE;
DROP TABLE IF EXISTS Raum_EventSlot CASCADE;
DROP TABLE IF EXISTS Raum CASCADE;
DROP TABLE IF EXISTS Gebaeude CASCADE;
DROP TABLE IF EXISTS EventSlot CASCADE;
DROP TABLE IF EXISTS Veranstaltung CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- 1. User Tabelle
CREATE TABLE "User"
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email              VARCHAR(255) UNIQUE NOT NULL,
    password_hash      VARCHAR(255)        NOT NULL,
    role               VARCHAR(50)         NOT NULL,
    first_name         VARCHAR(100),
    last_name          VARCHAR(100),
    version            BIGINT              NOT NULL DEFAULT 1,
    is_active          BOOLEAN                      DEFAULT TRUE,
    reset_token        VARCHAR(255),
    reset_token_expiry TIMESTAMP,
    biography          TEXT,
    job_role           VARCHAR(100),
    organisation       VARCHAR(255),
    slogan             VARCHAR(255),
    gruppe             VARCHAR(255)
);

-- 2. Veranstaltung
CREATE TABLE Veranstaltung
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    beginntAm      TIMESTAMP    NOT NULL,
    endetAm        TIMESTAMP,
    logo           VARCHAR(255),
    logo_link      VARCHAR(255),
    version        BIGINT       NOT NULL DEFAULT 1,
    UNIQUE (name, beginntAm)
);

-- 3. Gebaeude
CREATE TABLE Gebaeude
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) UNIQUE NOT NULL,
    typ          VARCHAR(50)         NOT NULL,
    strasse      VARCHAR(255)        NOT NULL,
    hausnummer   VARCHAR(20),
    postleitzahl VARCHAR(10)         NOT NULL,
    ort          VARCHAR(255)        NOT NULL,
    version      BIGINT              NOT NULL DEFAULT 1
);

-- 4. Zeit-Slots
CREATE TABLE EventSlot
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    startTime        TIMESTAMP NOT NULL,
    endTime          TIMESTAMP NOT NULL,
    description      VARCHAR(255),
    version          BIGINT    NOT NULL DEFAULT 1,
    veranstaltung_id BIGINT    NOT NULL,
    FOREIGN KEY (veranstaltung_id) REFERENCES Veranstaltung (id) ON DELETE CASCADE
);

-- 5. Räume
CREATE TABLE Raum
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    kapazitaet  INTEGER      NOT NULL,
    etage       VARCHAR(100),
    gebaeude_id BIGINT    NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 1,
    FOREIGN KEY (gebaeude_id) REFERENCES Gebaeude (id) ON DELETE CASCADE
);

-- 6. Relationen
CREATE TABLE Veranstaltung_Gebaeude
(
    veranstaltung_id BIGINT NOT NULL,
    gebaeude_id      BIGINT NOT NULL,
    PRIMARY KEY (veranstaltung_id, gebaeude_id),
    FOREIGN KEY (veranstaltung_id) REFERENCES Veranstaltung (id) ON DELETE CASCADE,
    FOREIGN KEY (gebaeude_id) REFERENCES Gebaeude (id) ON DELETE CASCADE
);

CREATE TABLE User_Veranstaltung (
    user_id BIGINT NOT NULL,
    veranstaltung_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, veranstaltung_id),
    FOREIGN KEY (user_id) REFERENCES "User" (id) ON DELETE CASCADE,
    FOREIGN KEY (veranstaltung_id) REFERENCES Veranstaltung (id) ON DELETE CASCADE
);

CREATE TABLE Raum_EventSlot
(
    raum_id      BIGINT NOT NULL,
    eventslot_id BIGINT NOT NULL,
    PRIMARY KEY (raum_id, eventslot_id),
    FOREIGN KEY (raum_id) REFERENCES Raum (id) ON DELETE CASCADE,
    FOREIGN KEY (eventslot_id) REFERENCES EventSlot (id) ON DELETE CASCADE
);

CREATE TABLE Teilnehmer_EventSlot
(
    teilnehmer_id BIGINT NOT NULL,
    eventslot_id  BIGINT NOT NULL,
    PRIMARY KEY (teilnehmer_id, eventslot_id),
    FOREIGN KEY (teilnehmer_id) REFERENCES "User" (id) ON DELETE CASCADE,
    FOREIGN KEY (eventslot_id) REFERENCES EventSlot (id) ON DELETE CASCADE
);

-- 7. Vorträge
CREATE TABLE Vortrag
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vortrag_typ       VARCHAR(50)  NOT NULL,
    referent_id       BIGINT      NOT NULL,
    veranstaltung_id  BIGINT      NOT NULL,
    titel             VARCHAR(255) NOT NULL,
    inhalt            TEXT,
    pflichtgruppe     VARCHAR(255),
    version           BIGINT       NOT NULL DEFAULT 1,
    pflichtraum_id    BIGINT,
    pflichtslot_id    BIGINT,
    wiederholbar      BOOLEAN               DEFAULT FALSE,
    maxWiederholungen INTEGER               DEFAULT 1,
    FOREIGN KEY (referent_id) REFERENCES "User" (id) ON DELETE CASCADE,
    FOREIGN KEY (veranstaltung_id) REFERENCES Veranstaltung (id) ON DELETE CASCADE,
    FOREIGN KEY (pflichtraum_id) REFERENCES Raum (id),
    FOREIGN KEY (pflichtslot_id) REFERENCES EventSlot (id)
);

CREATE TABLE Wahlvortrag_EventSlot
(
    vortrag_id   BIGINT NOT NULL,
    eventslot_id BIGINT NOT NULL,
    PRIMARY KEY (vortrag_id, eventslot_id),
    FOREIGN KEY (vortrag_id) REFERENCES Vortrag (id) ON DELETE CASCADE,
    FOREIGN KEY (eventslot_id) REFERENCES EventSlot (id) ON DELETE CASCADE
);

-- 8. Zuweisung
CREATE TABLE Zuweisung
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id BIGINT NOT NULL,
    vortrag_id    BIGINT NOT NULL,
    eventslot_id  BIGINT NOT NULL,
    raum_id       BIGINT NOT NULL,
    version       BIGINT  NOT NULL DEFAULT 1,
    FOREIGN KEY (teilnehmer_id) REFERENCES "User" (id) ON DELETE CASCADE,
    FOREIGN KEY (vortrag_id) REFERENCES Vortrag (id) ON DELETE CASCADE,
    FOREIGN KEY (eventslot_id) REFERENCES EventSlot (id) ON DELETE CASCADE,
    FOREIGN KEY (raum_id) REFERENCES Raum (id) ON DELETE CASCADE
);

-- 9. Prioritäten & Verfügbarkeit
CREATE TABLE Prioritaet
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teilnehmer_id BIGINT,
    vortrag_id    BIGINT,
    prioWert      INTEGER,
    lastUpdated   TIMESTAMP,
    version       BIGINT NOT NULL DEFAULT 1,
    FOREIGN KEY (teilnehmer_id) REFERENCES "User" (id) ON DELETE CASCADE,
    FOREIGN KEY (vortrag_id) REFERENCES Vortrag (id) ON DELETE CASCADE
);

CREATE TABLE Verfuegbarkeit
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    slot_id     BIGINT,
    isAvailable BOOLEAN         DEFAULT TRUE,
    version     BIGINT NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES "User" (id) ON DELETE CASCADE,
    FOREIGN KEY (slot_id) REFERENCES EventSlot (id) ON DELETE CASCADE
);