alter table if exists EventSlot
    drop constraint if exists FKj5mph080mx0f69snvixwm6bro;

alter table if exists Nutzer_Veranstaltung
    drop constraint if exists FKkhrm6bthspukyelg6m0hcxrn9;

alter table if exists Nutzer_Veranstaltung
    drop constraint if exists FK3ncjyr1g518d6cbp5moom636t;

alter table if exists Planungsergebnis
    drop constraint if exists FKm4eiuxbl64ox74y069kljc48u;

alter table if exists Prioritaet
    drop constraint if exists FKrgn2iupj4ndbav3fl0qt6uqyu;

alter table if exists Prioritaet
    drop constraint if exists FKje3bphsr0jtft452j2165u15x;

alter table if exists Raum
    drop constraint if exists FKp4omtwq0ahcw4ru0ji27xh3fi;

alter table if exists Raum_EventSlot
    drop constraint if exists FKfadfat2566py8gudfpmkd1laj;

alter table if exists Raum_EventSlot
    drop constraint if exists FKh6dn049v634jwiubho2negb4k;

alter table if exists RaumBelegbarkeit
    drop constraint if exists FK8k3imj6f2fflmj4vyfjgd2qic;

alter table if exists RaumBelegbarkeit
    drop constraint if exists FKf0ix2libxvsopyvyh9bvx01ng;

alter table if exists Teilnehmer_EventSlot
    drop constraint if exists FKg6crfd8nwhy1w8qawbcpngtsq;

alter table if exists Teilnehmer_EventSlot
    drop constraint if exists FK59g2qwpc3jnce4d1ec908984p;

alter table if exists Veranstaltung_Gebaeude
    drop constraint if exists FKb20732ctgp9axyb6mgej78yc8;

alter table if exists Veranstaltung_Gebaeude
    drop constraint if exists FKfgsbdf30p9h55k450oi713tnj;

alter table if exists Verfuegbarkeit
    drop constraint if exists FK7avsb9b9wh8iga60pix1wrthm;

alter table if exists Verfuegbarkeit
    drop constraint if exists FK2ax5ed7arptpst13b4k0ovejs;

alter table if exists Vortrag
    drop constraint if exists FKpe40i38wpnx4vssrjevk2umsw;

alter table if exists Vortrag
    drop constraint if exists FKce0t66m2ms7l9rsuwllfsk6v5;

alter table if exists Vortrag
    drop constraint if exists FKqf00utmxmbkfctdn5l3k2hltx;

alter table if exists Vortrag
    drop constraint if exists FK268xa39umt04uqnasmx1lcfep;

alter table if exists Wahlvortrag_EventSlot
    drop constraint if exists FKem51f0d439s8fkwmfp6b4jh1u;

alter table if exists Wahlvortrag_EventSlot
    drop constraint if exists FK2r3cfldr26gyw6aj2jr7oqv8l;

alter table if exists Zuweisung
    drop constraint if exists FK85ot2wrhpopnpejuhxda17epx;

alter table if exists Zuweisung
    drop constraint if exists FKm1g50o4rgoij77h0gtc595b4e;

alter table if exists Zuweisung
    drop constraint if exists FKnkhi7p2wuwtud3vpc3p0dro7d;

alter table if exists Zuweisung
    drop constraint if exists FKjkuptv90gdj3s5yl7irh45jix;

drop table if exists EventSlot cascade;

drop table if exists Gebaeude cascade;

drop table if exists Nutzer cascade;

drop table if exists Nutzer_Veranstaltung cascade;

drop table if exists Planungsergebnis cascade;

drop table if exists Prioritaet cascade;

drop table if exists Protokoll cascade;

drop table if exists Raum cascade;

drop table if exists Raum_EventSlot cascade;

drop table if exists RaumBelegbarkeit cascade;

drop table if exists Teilnehmer_EventSlot cascade;

drop table if exists Veranstaltung cascade;

drop table if exists Veranstaltung_Gebaeude cascade;

drop table if exists Verfuegbarkeit cascade;

drop table if exists Vortrag cascade;

drop table if exists Wahlvortrag_EventSlot cascade;

drop table if exists Zuweisung cascade;

create table EventSlot
(
    id               INTEGER generated by default as identity,
    veranstaltung_id INTEGER not null,
    version          bigint  not null,
    description      varchar(255),
    endTime          varchar(255),
    startTime        varchar(255),
    primary key (id)
);

create table Gebaeude
(
    id           INTEGER generated by default as identity,
    version      bigint       not null,
    hausnummer   varchar(255),
    name         varchar(255) not null unique,
    ort          varchar(255) not null,
    postleitzahl varchar(255) not null,
    strasse      varchar(255) not null,
    typ          varchar(255) not null check ((typ in ('SCHULE', 'KINO', 'SPORTHALLE', 'SAAL', 'EXTERN'))),
    primary key (id)
);

create table Nutzer
(
    is_active                 boolean,
    email_change_token_expiry timestamp(6),
    id                        INTEGER generated by default as identity,
    reset_token_expiry        timestamp(6),
    version                   bigint      not null,
    role                      varchar(31) not null check ((role in ('ADMIN', 'TEILNEHMER', 'REFERENT'))),
    biography                 TEXT,
    email                     varchar(255) unique,
    email_change_token        varchar(255),
    first_name                varchar(255),
    gruppe                    varchar(255),
    job_role                  varchar(255),
    last_name                 varchar(255),
    new_email                 varchar(255),
    organisation              varchar(255),
    password_hash             varchar(255),
    reset_token               varchar(255),
    slogan                    varchar(255),
    primary key (id),
    check (role <> 'ADMIN' or (is_active is not null)),
    check (role <> 'TEILNEHMER' or (is_active is not null)),
    check (role <> 'REFERENT' or (is_active is not null))
);

create table Nutzer_Veranstaltung
(
    nutzer_id        INTEGER not null,
    veranstaltung_id INTEGER not null,
    primary key (nutzer_id, veranstaltung_id)
);

create table Planungsergebnis
(
    timeout          integer      not null,
    id               INTEGER generated by default as identity,
    veranstaltung_id INTEGER      not null unique,
    version          bigint       not null,
    solver           varchar(255) not null,
    jsonErgebnis     oid          not null,
    primary key (id)
);

create table Prioritaet
(
    prio      integer not null,
    id            INTEGER generated by default as identity,
    teilnehmer_id INTEGER,
    vortrag_id    INTEGER,
    primary key (id)
);

create table Protokoll
(
    id         INTEGER generated by default as identity,
    referenzId bigint,
    akteur     varchar(255) not null,
    details    TEXT,
    ereignis   varchar(255) not null,
    kategorie  varchar(255) not null check ((kategorie in
                                             ('LOGIN', 'PLANUNG', 'STAMMDATEN', 'SECURITY', 'SYSTEM', 'VERANSTALTUNG',
                                              'NUTZER', 'VORTRAEGE', 'RAUM', 'GEBAEUDE'))),
    zeitpunkt  varchar(255) not null,
    primary key (id)
);

create table Raum
(
    kapazitaet  integer      not null,
    gebaeude_id INTEGER,
    id          INTEGER generated by default as identity,
    version     bigint       not null,
    etage       varchar(255),
    name        varchar(255) not null,
    primary key (id)
);

create table Raum_EventSlot
(
    eventslot_id INTEGER not null,
    raum_id      INTEGER not null,
    primary key (eventslot_id, raum_id)
);

create table RaumBelegbarkeit
(
    isBelegt boolean not null,
    id       INTEGER generated by default as identity,
    raum_id  INTEGER,
    slot_id  INTEGER,
    version  bigint  not null,
    primary key (id),
    unique (raum_id, slot_id)
);

create table Teilnehmer_EventSlot
(
    eventslot_id  INTEGER not null,
    teilnehmer_id INTEGER not null
);

create table Veranstaltung
(
    id                 INTEGER generated by default as identity,
    version            bigint       not null,
    beginntAm          varchar(255) not null,
    deadlineReferenten varchar(255),
    deadlineTeilnehmer varchar(255),
    endetAm            varchar(255),
    logo               varchar(255),
    logo_link          varchar(255),
    name               varchar(255) not null,
    primary key (id),
    unique (name, beginntAm)
);

create table Veranstaltung_Gebaeude
(
    gebaeude_id      INTEGER not null,
    veranstaltung_id INTEGER not null
);

create table Verfuegbarkeit
(
    isAvailable boolean not null,
    id          INTEGER generated by default as identity,
    slot_id     INTEGER,
    user_id     INTEGER,
    version     bigint  not null,
    primary key (id),
    unique (user_id, slot_id)
);

create table Vortrag
(
    maxWiederholungen integer,
    wiederholbar      boolean,
    id                INTEGER generated by default as identity,
    pflichtraum_id    INTEGER,
    pflichtslot_id    INTEGER,
    referent_id       INTEGER      not null,
    veranstaltung_id  INTEGER      not null,
    version           bigint       not null,
    vortrag_typ       varchar(31)  not null check ((vortrag_typ in ('PFLICHT', 'WAHL'))),
    inhalt            TEXT,
    pflichtgruppe     varchar(255),
    titel             varchar(255) not null,
    primary key (id),
    check (vortrag_typ <> 'PFLICHT' or (pflichtraum_id is not null and pflichtslot_id is not null)),
    check (vortrag_typ <> 'WAHL' or (maxWiederholungen is not null and wiederholbar is not null))
);

create table Wahlvortrag_EventSlot
(
    eventslot_id INTEGER not null,
    vortrag_id   INTEGER not null
);

create table Zuweisung
(
    eventslot_id  INTEGER not null,
    id            INTEGER generated by default as identity,
    raum_id       INTEGER not null,
    teilnehmer_id INTEGER not null,
    version       bigint  not null,
    vortrag_id    INTEGER not null,
    primary key (id)
);

alter table if exists EventSlot
    add constraint FKj5mph080mx0f69snvixwm6bro
        foreign key (veranstaltung_id)
            references Veranstaltung;

alter table if exists Nutzer_Veranstaltung
    add constraint FKkhrm6bthspukyelg6m0hcxrn9
        foreign key (veranstaltung_id)
            references Veranstaltung;

alter table if exists Nutzer_Veranstaltung
    add constraint FK3ncjyr1g518d6cbp5moom636t
        foreign key (nutzer_id)
            references Nutzer;

alter table if exists Planungsergebnis
    add constraint FKm4eiuxbl64ox74y069kljc48u
        foreign key (veranstaltung_id)
            references Veranstaltung;

alter table if exists Prioritaet
    add constraint FKrgn2iupj4ndbav3fl0qt6uqyu
        foreign key (teilnehmer_id)
            references Nutzer;

alter table if exists Prioritaet
    add constraint FKje3bphsr0jtft452j2165u15x
        foreign key (vortrag_id)
            references Vortrag;

alter table if exists Raum
    add constraint FKp4omtwq0ahcw4ru0ji27xh3fi
        foreign key (gebaeude_id)
            references Gebaeude;

alter table if exists Raum_EventSlot
    add constraint FKfadfat2566py8gudfpmkd1laj
        foreign key (eventslot_id)
            references EventSlot;

alter table if exists Raum_EventSlot
    add constraint FKh6dn049v634jwiubho2negb4k
        foreign key (raum_id)
            references Raum;

alter table if exists RaumBelegbarkeit
    add constraint FK8k3imj6f2fflmj4vyfjgd2qic
        foreign key (raum_id)
            references Raum;

alter table if exists RaumBelegbarkeit
    add constraint FKf0ix2libxvsopyvyh9bvx01ng
        foreign key (slot_id)
            references EventSlot;

alter table if exists Teilnehmer_EventSlot
    add constraint FKg6crfd8nwhy1w8qawbcpngtsq
        foreign key (eventslot_id)
            references EventSlot;

alter table if exists Teilnehmer_EventSlot
    add constraint FK59g2qwpc3jnce4d1ec908984p
        foreign key (teilnehmer_id)
            references Nutzer;

alter table if exists Veranstaltung_Gebaeude
    add constraint FKb20732ctgp9axyb6mgej78yc8
        foreign key (gebaeude_id)
            references Gebaeude;

alter table if exists Veranstaltung_Gebaeude
    add constraint FKfgsbdf30p9h55k450oi713tnj
        foreign key (veranstaltung_id)
            references Veranstaltung;

alter table if exists Verfuegbarkeit
    add constraint FK7avsb9b9wh8iga60pix1wrthm
        foreign key (user_id)
            references Nutzer;

alter table if exists Verfuegbarkeit
    add constraint FK2ax5ed7arptpst13b4k0ovejs
        foreign key (slot_id)
            references EventSlot;

alter table if exists Vortrag
    add constraint FKpe40i38wpnx4vssrjevk2umsw
        foreign key (referent_id)
            references Nutzer;

alter table if exists Vortrag
    add constraint FKce0t66m2ms7l9rsuwllfsk6v5
        foreign key (veranstaltung_id)
            references Veranstaltung;

alter table if exists Vortrag
    add constraint FKqf00utmxmbkfctdn5l3k2hltx
        foreign key (pflichtraum_id)
            references Raum;

alter table if exists Vortrag
    add constraint FK268xa39umt04uqnasmx1lcfep
        foreign key (pflichtslot_id)
            references EventSlot;

alter table if exists Wahlvortrag_EventSlot
    add constraint FKem51f0d439s8fkwmfp6b4jh1u
        foreign key (eventslot_id)
            references EventSlot;

alter table if exists Wahlvortrag_EventSlot
    add constraint FK2r3cfldr26gyw6aj2jr7oqv8l
        foreign key (vortrag_id)
            references Vortrag;

alter table if exists Zuweisung
    add constraint FK85ot2wrhpopnpejuhxda17epx
        foreign key (raum_id)
            references Raum;

alter table if exists Zuweisung
    add constraint FKm1g50o4rgoij77h0gtc595b4e
        foreign key (eventslot_id)
            references EventSlot;

alter table if exists Zuweisung
    add constraint FKnkhi7p2wuwtud3vpc3p0dro7d
        foreign key (teilnehmer_id)
            references Nutzer;

alter table if exists Zuweisung
    add constraint FKjkuptv90gdj3s5yl7irh45jix
        foreign key (vortrag_id)
            references Vortrag;
