quarkus.http.port=9000

# CORS aktivieren fuer Frontend-Entwicklung auf Port 5173
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# SQLite Konfiguration
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:/Users/kreyj/Java/berufsorientierung/vortragsmanager/vortragsmanager.db
quarkus.datasource.jdbc.max-size=2
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.acquisition-timeout=30S
quarkus.datasource.jdbc.additional-jdbc-properties.foreign_keys=true
quarkus.datasource.jdbc.additional-jdbc-properties.busy_timeout=30000

# Hibernate Konfiguration
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.dialect=org.hibernate.community.dialect.SQLiteDialect
#quarkus.hibernate-orm.log.sql=true

# Security
quarkus.smallrye-jwt.enabled=true
# JWT signing/verifying
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://vortragsmanager.kreyj

# Test
quarkus.http.test-timeout=60s

# Logging
quarkus.log.category."io.quarkus.rest.request".level=DEBUG
quarkus.http.access-log.enabled=true

# HTTP Payload Logging im Dev-Modus
%dev.quarkus.log.category."kreyj.vortragsmanager.resource".level=DEBUG
%dev.quarkus.log.category."kreyj.vortragsmanager.service".level=DEBUG

# Frontend/Quinoa
quarkus.quinoa.ui-dir=../frontend
quarkus.quinoa.package-manager=npm
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.build-dir=dist
quarkus.quinoa.history-navigation=true

# Mailpit-Konfig
quarkus.mailer.devservices.enabled=false
quarkus.mailer.devservices.image-name=axllent/mailpit:latest
quarkus.mailer.devservices.ports=1025,8025
quarkus.mailer.devservices.volumes=mailpit_data:/data
