quarkus.http.port=9000

# CORS aktivieren fuer Frontend-Entwicklung auf Port 5173
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,PUT,POST,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# Datenbank Konfiguration (Standard: PostgreSQL)
#quarkus.datasource.username=${DB_USER:vortragsmanager}
#quarkus.datasource.password=${DB_PASSWORD:secret}
#quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:vortragsmanager}
#quarkus.datasource.jdbc.max-size=10

# Dev-Modus: Nutzt standardm‰ﬂig Postgres Dev Services (Docker)


# Flyway Konfiguration
#quarkus.flyway.migrate-at-start=true

# Hibernate Konfiguration
#quarkus.hibernate-orm.database.generation=drop-and-create
# quarkus.hibernate-orm.log.sql=true

# Security
quarkus.smallrye-jwt.enabled=true
# JWT signing/verifying
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://vortragsmanager.kreyj

# Test
quarkus.http.test-timeout=60s

# Logging
quarkus.log.category."io.quarkus.rest.request".level=DEBUG
quarkus.http.access-log.enabled=true

# HTTP Payload Logging im Dev-Modus
%dev.quarkus.log.category."kreyj.vortragsmanager.resource".level=DEBUG
%dev.quarkus.log.category."kreyj.vortragsmanager.service".level=DEBUG

# Frontend/Quinoa
quarkus.quinoa.ui-dir=../frontend
quarkus.quinoa.package-manager=npm
quarkus.quinoa.dev-server.port=5173
quarkus.quinoa.build-dir=dist
quarkus.quinoa.history-navigation=true

# Mailer setup (Mailpit must be running - locally)
quarkus.mailer.host=localhost
quarkus.mailer.port=1025
quarkus.mailer.from=juergenkrey@yahoo.de
