#!/bin/sh
set -e

case "$1" in
    remove)
        systemctl stop konfplan-mailpit.service || true
        docker rm -f konfplan-mailpit > /dev/null 2>&1 || true
        systemctl daemon-reload || true
        ;;
    purge)
        systemctl disable konfplan-mailpit.service || true
        ;;
esac

exit 0
